%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'BOKDSGE2014_0722';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('BOKDSGE2014_0722.log');
M_.exo_names = 'er';
M_.exo_names_tex = 'er';
M_.exo_names_long = 'er';
M_.exo_names = char(M_.exo_names, 'ea');
M_.exo_names_tex = char(M_.exo_names_tex, 'ea');
M_.exo_names_long = char(M_.exo_names_long, 'ea');
M_.exo_names = char(M_.exo_names, 'etrend');
M_.exo_names_tex = char(M_.exo_names_tex, 'etrend');
M_.exo_names_long = char(M_.exo_names_long, 'etrend');
M_.exo_names = char(M_.exo_names, 'einv');
M_.exo_names_tex = char(M_.exo_names_tex, 'einv');
M_.exo_names_long = char(M_.exo_names_long, 'einv');
M_.exo_names = char(M_.exo_names, 'ec');
M_.exo_names_tex = char(M_.exo_names_tex, 'ec');
M_.exo_names_long = char(M_.exo_names_long, 'ec');
M_.exo_names = char(M_.exo_names, 'einf');
M_.exo_names_tex = char(M_.exo_names_tex, 'einf');
M_.exo_names_long = char(M_.exo_names_long, 'einf');
M_.exo_names = char(M_.exo_names, 'en');
M_.exo_names_tex = char(M_.exo_names_tex, 'en');
M_.exo_names_long = char(M_.exo_names_long, 'en');
M_.exo_names = char(M_.exo_names, 'einff');
M_.exo_names_tex = char(M_.exo_names_tex, 'einff');
M_.exo_names_long = char(M_.exo_names_long, 'einff');
M_.exo_names = char(M_.exo_names, 'ex');
M_.exo_names_tex = char(M_.exo_names_tex, 'ex');
M_.exo_names_long = char(M_.exo_names_long, 'ex');
M_.exo_names = char(M_.exo_names, 'eg');
M_.exo_names_tex = char(M_.exo_names_tex, 'eg');
M_.exo_names_long = char(M_.exo_names_long, 'eg');
M_.exo_names = char(M_.exo_names, 'epr');
M_.exo_names_tex = char(M_.exo_names_tex, 'epr');
M_.exo_names_long = char(M_.exo_names_long, 'epr');
M_.exo_names = char(M_.exo_names, 'eystar');
M_.exo_names_tex = char(M_.exo_names_tex, 'eystar');
M_.exo_names_long = char(M_.exo_names_long, 'eystar');
M_.exo_names = char(M_.exo_names, 'erstar');
M_.exo_names_tex = char(M_.exo_names_tex, 'erstar');
M_.exo_names_long = char(M_.exo_names_long, 'erstar');
M_.exo_names = char(M_.exo_names, 'epistar');
M_.exo_names_tex = char(M_.exo_names_tex, 'epistar');
M_.exo_names_long = char(M_.exo_names_long, 'epistar');
M_.exo_names = char(M_.exo_names, 'ecp');
M_.exo_names_tex = char(M_.exo_names_tex, 'ecp');
M_.exo_names_long = char(M_.exo_names_long, 'ecp');
M_.exo_names = char(M_.exo_names, 'ew');
M_.exo_names_tex = char(M_.exo_names_tex, 'ew');
M_.exo_names_long = char(M_.exo_names_long, 'ew');
M_.exo_names = char(M_.exo_names, 'emc');
M_.exo_names_tex = char(M_.exo_names_tex, 'emc');
M_.exo_names_long = char(M_.exo_names_long, 'emc');
M_.exo_names = char(M_.exo_names, 'epx');
M_.exo_names_tex = char(M_.exo_names_tex, 'epx');
M_.exo_names_long = char(M_.exo_names_long, 'epx');
M_.endo_names = 'Y';
M_.endo_names_tex = 'Y';
M_.endo_names_long = 'Y';
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 'N');
M_.endo_names_tex = char(M_.endo_names_tex, 'N');
M_.endo_names_long = char(M_.endo_names_long, 'N');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'W');
M_.endo_names_tex = char(M_.endo_names_tex, 'W');
M_.endo_names_long = char(M_.endo_names_long, 'W');
M_.endo_names = char(M_.endo_names, 'Rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk');
M_.endo_names_long = char(M_.endo_names_long, 'Rk');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'dA');
M_.endo_names_tex = char(M_.endo_names_tex, 'dA');
M_.endo_names_long = char(M_.endo_names_long, 'dA');
M_.endo_names = char(M_.endo_names, 'dP');
M_.endo_names_tex = char(M_.endo_names_tex, 'dP');
M_.endo_names_long = char(M_.endo_names_long, 'dP');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'MC');
M_.endo_names_tex = char(M_.endo_names_tex, 'MC');
M_.endo_names_long = char(M_.endo_names_long, 'MC');
M_.endo_names = char(M_.endo_names, 'P');
M_.endo_names_tex = char(M_.endo_names_tex, 'P');
M_.endo_names_long = char(M_.endo_names_long, 'P');
M_.endo_names = char(M_.endo_names, 'X1');
M_.endo_names_tex = char(M_.endo_names_tex, 'X1');
M_.endo_names_long = char(M_.endo_names_long, 'X1');
M_.endo_names = char(M_.endo_names, 'X2');
M_.endo_names_tex = char(M_.endo_names_tex, 'X2');
M_.endo_names_long = char(M_.endo_names_long, 'X2');
M_.endo_names = char(M_.endo_names, 'SS');
M_.endo_names_tex = char(M_.endo_names_tex, 'SS');
M_.endo_names_long = char(M_.endo_names_long, 'SS');
M_.endo_names = char(M_.endo_names, 'ERE');
M_.endo_names_tex = char(M_.endo_names_tex, 'ERE');
M_.endo_names_long = char(M_.endo_names_long, 'ERE');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'RR');
M_.endo_names_tex = char(M_.endo_names_tex, 'RR');
M_.endo_names_long = char(M_.endo_names_long, 'RR');
M_.endo_names = char(M_.endo_names, 'S');
M_.endo_names_tex = char(M_.endo_names_tex, 'S');
M_.endo_names_long = char(M_.endo_names_long, 'S');
M_.endo_names = char(M_.endo_names, 'Px');
M_.endo_names_tex = char(M_.endo_names_tex, 'Px');
M_.endo_names_long = char(M_.endo_names_long, 'Px');
M_.endo_names = char(M_.endo_names, 'Pm');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pm');
M_.endo_names_long = char(M_.endo_names_long, 'Pm');
M_.endo_names = char(M_.endo_names, 'X');
M_.endo_names_tex = char(M_.endo_names_tex, 'X');
M_.endo_names_long = char(M_.endo_names_long, 'X');
M_.endo_names = char(M_.endo_names, 'PPx');
M_.endo_names_tex = char(M_.endo_names_tex, 'PPx');
M_.endo_names_long = char(M_.endo_names_long, 'PPx');
M_.endo_names = char(M_.endo_names, 'PPm');
M_.endo_names_tex = char(M_.endo_names_tex, 'PPm');
M_.endo_names_long = char(M_.endo_names_long, 'PPm');
M_.endo_names = char(M_.endo_names, 'RRw');
M_.endo_names_tex = char(M_.endo_names_tex, 'RRw');
M_.endo_names_long = char(M_.endo_names_long, 'RRw');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q');
M_.endo_names_long = char(M_.endo_names_long, 'Q');
M_.endo_names = char(M_.endo_names, 'Inv');
M_.endo_names_tex = char(M_.endo_names_tex, 'Inv');
M_.endo_names_long = char(M_.endo_names_long, 'Inv');
M_.endo_names = char(M_.endo_names, 'Re');
M_.endo_names_tex = char(M_.endo_names_tex, 'Re');
M_.endo_names_long = char(M_.endo_names_long, 'Re');
M_.endo_names = char(M_.endo_names, 'NN');
M_.endo_names_tex = char(M_.endo_names_tex, 'NN');
M_.endo_names_long = char(M_.endo_names_long, 'NN');
M_.endo_names = char(M_.endo_names, 'Cd');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cd');
M_.endo_names_long = char(M_.endo_names_long, 'Cd');
M_.endo_names = char(M_.endo_names, 'Cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cf');
M_.endo_names_long = char(M_.endo_names_long, 'Cf');
M_.endo_names = char(M_.endo_names, 'Pc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pc');
M_.endo_names_long = char(M_.endo_names_long, 'Pc');
M_.endo_names = char(M_.endo_names, 'Pf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pf');
M_.endo_names_long = char(M_.endo_names_long, 'Pf');
M_.endo_names = char(M_.endo_names, 'dPd');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPd');
M_.endo_names_long = char(M_.endo_names_long, 'dPd');
M_.endo_names = char(M_.endo_names, 'dPf');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPf');
M_.endo_names_long = char(M_.endo_names_long, 'dPf');
M_.endo_names = char(M_.endo_names, 'PPf');
M_.endo_names_tex = char(M_.endo_names_tex, 'PPf');
M_.endo_names_long = char(M_.endo_names_long, 'PPf');
M_.endo_names = char(M_.endo_names, 'PP_invf');
M_.endo_names_tex = char(M_.endo_names_tex, 'PP\_invf');
M_.endo_names_long = char(M_.endo_names_long, 'PP_invf');
M_.endo_names = char(M_.endo_names, 'X1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'X1f');
M_.endo_names_long = char(M_.endo_names_long, 'X1f');
M_.endo_names = char(M_.endo_names, 'X2f');
M_.endo_names_tex = char(M_.endo_names_tex, 'X2f');
M_.endo_names_long = char(M_.endo_names_long, 'X2f');
M_.endo_names = char(M_.endo_names, 'Invd');
M_.endo_names_tex = char(M_.endo_names_tex, 'Invd');
M_.endo_names_long = char(M_.endo_names_long, 'Invd');
M_.endo_names = char(M_.endo_names, 'Invf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Invf');
M_.endo_names_long = char(M_.endo_names_long, 'Invf');
M_.endo_names = char(M_.endo_names, 'Pinv');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pinv');
M_.endo_names_long = char(M_.endo_names_long, 'Pinv');
M_.endo_names = char(M_.endo_names, 'P_invf');
M_.endo_names_tex = char(M_.endo_names_tex, 'P\_invf');
M_.endo_names_long = char(M_.endo_names_long, 'P_invf');
M_.endo_names = char(M_.endo_names, 'dPinv');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPinv');
M_.endo_names_long = char(M_.endo_names_long, 'dPinv');
M_.endo_names = char(M_.endo_names, 'dP_invf');
M_.endo_names_tex = char(M_.endo_names_tex, 'dP\_invf');
M_.endo_names_long = char(M_.endo_names_long, 'dP_invf');
M_.endo_names = char(M_.endo_names, 'X1_invf');
M_.endo_names_tex = char(M_.endo_names_tex, 'X1\_invf');
M_.endo_names_long = char(M_.endo_names_long, 'X1_invf');
M_.endo_names = char(M_.endo_names, 'X2_invf');
M_.endo_names_tex = char(M_.endo_names_tex, 'X2\_invf');
M_.endo_names_long = char(M_.endo_names_long, 'X2_invf');
M_.endo_names = char(M_.endo_names, 'Imp');
M_.endo_names_tex = char(M_.endo_names_tex, 'Imp');
M_.endo_names_long = char(M_.endo_names_long, 'Imp');
M_.endo_names = char(M_.endo_names, 'Ystar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ystar');
M_.endo_names_long = char(M_.endo_names_long, 'Ystar');
M_.endo_names = char(M_.endo_names, 'Rstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar');
M_.endo_names = char(M_.endo_names, 'Pistar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pistar');
M_.endo_names_long = char(M_.endo_names_long, 'Pistar');
M_.endo_names = char(M_.endo_names, 'Za');
M_.endo_names_tex = char(M_.endo_names_tex, 'Za');
M_.endo_names_long = char(M_.endo_names_long, 'Za');
M_.endo_names = char(M_.endo_names, 'Zinv');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zinv');
M_.endo_names_long = char(M_.endo_names_long, 'Zinv');
M_.endo_names = char(M_.endo_names, 'Zc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zc');
M_.endo_names_long = char(M_.endo_names_long, 'Zc');
M_.endo_names = char(M_.endo_names, 'Zinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zinf');
M_.endo_names_long = char(M_.endo_names_long, 'Zinf');
M_.endo_names = char(M_.endo_names, 'Zn');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zn');
M_.endo_names_long = char(M_.endo_names_long, 'Zn');
M_.endo_names = char(M_.endo_names, 'Zinff');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zinff');
M_.endo_names_long = char(M_.endo_names_long, 'Zinff');
M_.endo_names = char(M_.endo_names, 'Zx');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zx');
M_.endo_names_long = char(M_.endo_names_long, 'Zx');
M_.endo_names = char(M_.endo_names, 'Zg');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zg');
M_.endo_names_long = char(M_.endo_names_long, 'Zg');
M_.endo_names = char(M_.endo_names, 'Zw');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zw');
M_.endo_names_long = char(M_.endo_names_long, 'Zw');
M_.endo_names = char(M_.endo_names, 'Zcp');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zcp');
M_.endo_names_long = char(M_.endo_names_long, 'Zcp');
M_.endo_names = char(M_.endo_names, 'Zmc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zmc');
M_.endo_names_long = char(M_.endo_names_long, 'Zmc');
M_.endo_names = char(M_.endo_names, 'Y_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Y_obs');
M_.endo_names = char(M_.endo_names, 'R_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_obs');
M_.endo_names = char(M_.endo_names, 'dP_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'dP\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'dP_obs');
M_.endo_names = char(M_.endo_names, 'C_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'C_obs');
M_.endo_names = char(M_.endo_names, 'Inv_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Inv\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Inv_obs');
M_.endo_names = char(M_.endo_names, 'NN_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'NN\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'NN_obs');
M_.endo_names = char(M_.endo_names, 'dPf_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPf\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'dPf_obs');
M_.endo_names = char(M_.endo_names, 'X_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'X\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'X_obs');
M_.endo_names = char(M_.endo_names, 'dPinv_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPinv\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'dPinv_obs');
M_.endo_names = char(M_.endo_names, 'S_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'S\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'S_obs');
M_.endo_names = char(M_.endo_names, 'Ystar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ystar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Ystar_obs');
M_.endo_names = char(M_.endo_names, 'Rstar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar_obs');
M_.endo_names = char(M_.endo_names, 'Pistar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pistar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Pistar_obs');
M_.endo_names = char(M_.endo_names, 'W_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'W\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'W_obs');
M_.endo_names = char(M_.endo_names, 'G_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'G\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'G_obs');
M_.endo_names = char(M_.endo_names, 'SP_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'SP\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'SP_obs');
M_.endo_names = char(M_.endo_names, 'dPx_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPx\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'dPx_obs');
M_.endo_names = char(M_.endo_names, 'GAPeff');
M_.endo_names_tex = char(M_.endo_names_tex, 'GAPeff');
M_.endo_names_long = char(M_.endo_names_long, 'GAPeff');
M_.endo_names = char(M_.endo_names, 'Y_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_e');
M_.endo_names_long = char(M_.endo_names_long, 'Y_e');
M_.endo_names = char(M_.endo_names, 'Ce');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ce');
M_.endo_names_long = char(M_.endo_names_long, 'Ce');
M_.endo_names = char(M_.endo_names, 'Ne');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ne');
M_.endo_names_long = char(M_.endo_names_long, 'Ne');
M_.endo_names = char(M_.endo_names, 'LAMe');
M_.endo_names_tex = char(M_.endo_names_tex, 'LAMe');
M_.endo_names_long = char(M_.endo_names_long, 'LAMe');
M_.endo_names = char(M_.endo_names, 'We');
M_.endo_names_tex = char(M_.endo_names_tex, 'We');
M_.endo_names_long = char(M_.endo_names_long, 'We');
M_.endo_names = char(M_.endo_names, 'R_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_e');
M_.endo_names_long = char(M_.endo_names_long, 'R_e');
M_.endo_names = char(M_.endo_names, 'Ke');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ke');
M_.endo_names_long = char(M_.endo_names_long, 'Ke');
M_.endo_names = char(M_.endo_names, 'Inve');
M_.endo_names_tex = char(M_.endo_names_tex, 'Inve');
M_.endo_names_long = char(M_.endo_names_long, 'Inve');
M_.endo_names = char(M_.endo_names, 'Rke');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rke');
M_.endo_names_long = char(M_.endo_names_long, 'Rke');
M_.endo_names = char(M_.endo_names, 'Qe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Qe');
M_.endo_names_long = char(M_.endo_names_long, 'Qe');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'X1w');
M_.endo_names_tex = char(M_.endo_names_tex, 'X1w');
M_.endo_names_long = char(M_.endo_names_long, 'X1w');
M_.endo_names = char(M_.endo_names, 'X1ww');
M_.endo_names_tex = char(M_.endo_names_tex, 'X1ww');
M_.endo_names_long = char(M_.endo_names_long, 'X1ww');
M_.endo_names = char(M_.endo_names, 'X2w');
M_.endo_names_tex = char(M_.endo_names_tex, 'X2w');
M_.endo_names_long = char(M_.endo_names_long, 'X2w');
M_.endo_names = char(M_.endo_names, 'X2ww');
M_.endo_names_tex = char(M_.endo_names_tex, 'X2ww');
M_.endo_names_long = char(M_.endo_names_long, 'X2ww');
M_.endo_names = char(M_.endo_names, 'ut');
M_.endo_names_tex = char(M_.endo_names_tex, 'ut');
M_.endo_names_long = char(M_.endo_names_long, 'ut');
M_.endo_names = char(M_.endo_names, 'Xd');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xd');
M_.endo_names_long = char(M_.endo_names_long, 'Xd');
M_.endo_names = char(M_.endo_names, 'Xm');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xm');
M_.endo_names_long = char(M_.endo_names_long, 'Xm');
M_.endo_names = char(M_.endo_names, 'Pxx');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pxx');
M_.endo_names_long = char(M_.endo_names_long, 'Pxx');
M_.endo_names = char(M_.endo_names, 'dPx');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPx');
M_.endo_names_long = char(M_.endo_names_long, 'dPx');
M_.endo_names = char(M_.endo_names, 'Ystar_or');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ystar\_or');
M_.endo_names_long = char(M_.endo_names_long, 'Ystar_or');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_3');
M_.param_names = 'bet';
M_.param_names_tex = 'bet';
M_.param_names_long = 'bet';
M_.param_names = char(M_.param_names, 'del');
M_.param_names_tex = char(M_.param_names_tex, 'del');
M_.param_names_long = char(M_.param_names_long, 'del');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names_long = char(M_.param_names_long, 'psi');
M_.param_names = char(M_.param_names, 'alpk');
M_.param_names_tex = char(M_.param_names_tex, 'alpk');
M_.param_names_long = char(M_.param_names_long, 'alpk');
M_.param_names = char(M_.param_names, 'chic');
M_.param_names_tex = char(M_.param_names_tex, 'chic');
M_.param_names_long = char(M_.param_names_long, 'chic');
M_.param_names = char(M_.param_names, 'eps');
M_.param_names_tex = char(M_.param_names_tex, 'eps');
M_.param_names_long = char(M_.param_names_long, 'eps');
M_.param_names = char(M_.param_names, 'epsf');
M_.param_names_tex = char(M_.param_names_tex, 'epsf');
M_.param_names_long = char(M_.param_names_long, 'epsf');
M_.param_names = char(M_.param_names, 'the');
M_.param_names_tex = char(M_.param_names_tex, 'the');
M_.param_names_long = char(M_.param_names_long, 'the');
M_.param_names = char(M_.param_names, 'thef');
M_.param_names_tex = char(M_.param_names_tex, 'thef');
M_.param_names_long = char(M_.param_names_long, 'thef');
M_.param_names = char(M_.param_names, 'rhop');
M_.param_names_tex = char(M_.param_names_tex, 'rhop');
M_.param_names_long = char(M_.param_names_long, 'rhop');
M_.param_names = char(M_.param_names, 'rhoy');
M_.param_names_tex = char(M_.param_names_tex, 'rhoy');
M_.param_names_long = char(M_.param_names_long, 'rhoy');
M_.param_names = char(M_.param_names, 'rhor');
M_.param_names_tex = char(M_.param_names_tex, 'rhor');
M_.param_names_long = char(M_.param_names_long, 'rhor');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'zet');
M_.param_names_tex = char(M_.param_names_tex, 'zet');
M_.param_names_long = char(M_.param_names_long, 'zet');
M_.param_names = char(M_.param_names, 'psi_x');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_x');
M_.param_names_long = char(M_.param_names_long, 'psi_x');
M_.param_names = char(M_.param_names, 'psi_px');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_px');
M_.param_names_long = char(M_.param_names_long, 'psi_px');
M_.param_names = char(M_.param_names, 'chik');
M_.param_names_tex = char(M_.param_names_tex, 'chik');
M_.param_names_long = char(M_.param_names_long, 'chik');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'gamma1');
M_.param_names_tex = char(M_.param_names_tex, 'gamma1');
M_.param_names_long = char(M_.param_names_long, 'gamma1');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'alp_c');
M_.param_names_tex = char(M_.param_names_tex, 'alp\_c');
M_.param_names_long = char(M_.param_names_long, 'alp_c');
M_.param_names = char(M_.param_names, 'rho_c');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_c');
M_.param_names_long = char(M_.param_names_long, 'rho_c');
M_.param_names = char(M_.param_names, 'alp_i');
M_.param_names_tex = char(M_.param_names_tex, 'alp\_i');
M_.param_names_long = char(M_.param_names_long, 'alp_i');
M_.param_names = char(M_.param_names, 'rho_i');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_i');
M_.param_names_long = char(M_.param_names_long, 'rho_i');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'del_e');
M_.param_names_tex = char(M_.param_names_tex, 'del\_e');
M_.param_names_long = char(M_.param_names_long, 'del_e');
M_.param_names = char(M_.param_names, 'iota');
M_.param_names_tex = char(M_.param_names_tex, 'iota');
M_.param_names_long = char(M_.param_names_long, 'iota');
M_.param_names = char(M_.param_names, 'pi_target');
M_.param_names_tex = char(M_.param_names_tex, 'pi\_target');
M_.param_names_long = char(M_.param_names_long, 'pi_target');
M_.param_names = char(M_.param_names, 'thew');
M_.param_names_tex = char(M_.param_names_tex, 'thew');
M_.param_names_long = char(M_.param_names_long, 'thew');
M_.param_names = char(M_.param_names, 'epsw');
M_.param_names_tex = char(M_.param_names_tex, 'epsw');
M_.param_names_long = char(M_.param_names_long, 'epsw');
M_.param_names = char(M_.param_names, 'v');
M_.param_names_tex = char(M_.param_names_tex, 'v');
M_.param_names_long = char(M_.param_names_long, 'v');
M_.param_names = char(M_.param_names, 'gam');
M_.param_names_tex = char(M_.param_names_tex, 'gam');
M_.param_names_long = char(M_.param_names_long, 'gam');
M_.param_names = char(M_.param_names, 'gam2');
M_.param_names_tex = char(M_.param_names_tex, 'gam2');
M_.param_names_long = char(M_.param_names_long, 'gam2');
M_.param_names = char(M_.param_names, 'zet2');
M_.param_names_tex = char(M_.param_names_tex, 'zet2');
M_.param_names_long = char(M_.param_names_long, 'zet2');
M_.param_names = char(M_.param_names, 'alpx');
M_.param_names_tex = char(M_.param_names_tex, 'alpx');
M_.param_names_long = char(M_.param_names_long, 'alpx');
M_.param_names = char(M_.param_names, 'etax');
M_.param_names_tex = char(M_.param_names_tex, 'etax');
M_.param_names_long = char(M_.param_names_long, 'etax');
M_.param_names = char(M_.param_names, 'rhogam');
M_.param_names_tex = char(M_.param_names_tex, 'rhogam');
M_.param_names_long = char(M_.param_names_long, 'rhogam');
M_.param_names = char(M_.param_names, 'rhoa');
M_.param_names_tex = char(M_.param_names_tex, 'rhoa');
M_.param_names_long = char(M_.param_names_long, 'rhoa');
M_.param_names = char(M_.param_names, 'rhoinv');
M_.param_names_tex = char(M_.param_names_tex, 'rhoinv');
M_.param_names_long = char(M_.param_names_long, 'rhoinv');
M_.param_names = char(M_.param_names, 'rhoc');
M_.param_names_tex = char(M_.param_names_tex, 'rhoc');
M_.param_names_long = char(M_.param_names_long, 'rhoc');
M_.param_names = char(M_.param_names, 'rhoinf');
M_.param_names_tex = char(M_.param_names_tex, 'rhoinf');
M_.param_names_long = char(M_.param_names_long, 'rhoinf');
M_.param_names = char(M_.param_names, 'rhon');
M_.param_names_tex = char(M_.param_names_tex, 'rhon');
M_.param_names_long = char(M_.param_names_long, 'rhon');
M_.param_names = char(M_.param_names, 'rhoinff');
M_.param_names_tex = char(M_.param_names_tex, 'rhoinff');
M_.param_names_long = char(M_.param_names_long, 'rhoinff');
M_.param_names = char(M_.param_names, 'rhox');
M_.param_names_tex = char(M_.param_names_tex, 'rhox');
M_.param_names_long = char(M_.param_names_long, 'rhox');
M_.param_names = char(M_.param_names, 'rhopinv');
M_.param_names_tex = char(M_.param_names_tex, 'rhopinv');
M_.param_names_long = char(M_.param_names_long, 'rhopinv');
M_.param_names = char(M_.param_names, 'g_ss');
M_.param_names_tex = char(M_.param_names_tex, 'g\_ss');
M_.param_names_long = char(M_.param_names_long, 'g_ss');
M_.param_names = char(M_.param_names, 'rhog');
M_.param_names_tex = char(M_.param_names_tex, 'rhog');
M_.param_names_long = char(M_.param_names_long, 'rhog');
M_.param_names = char(M_.param_names, 'rhopr');
M_.param_names_tex = char(M_.param_names_tex, 'rhopr');
M_.param_names_long = char(M_.param_names_long, 'rhopr');
M_.param_names = char(M_.param_names, 'rhow');
M_.param_names_tex = char(M_.param_names_tex, 'rhow');
M_.param_names_long = char(M_.param_names_long, 'rhow');
M_.param_names = char(M_.param_names, 'rhocp');
M_.param_names_tex = char(M_.param_names_tex, 'rhocp');
M_.param_names_long = char(M_.param_names_long, 'rhocp');
M_.param_names = char(M_.param_names, 'rhomc');
M_.param_names_tex = char(M_.param_names_tex, 'rhomc');
M_.param_names_long = char(M_.param_names_long, 'rhomc');
M_.param_names = char(M_.param_names, 'SIGMAr');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAr');
M_.param_names_long = char(M_.param_names_long, 'SIGMAr');
M_.param_names = char(M_.param_names, 'SIGMAa');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAa');
M_.param_names_long = char(M_.param_names_long, 'SIGMAa');
M_.param_names = char(M_.param_names, 'SIGMAinv');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAinv');
M_.param_names_long = char(M_.param_names_long, 'SIGMAinv');
M_.param_names = char(M_.param_names, 'SIGMAc');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAc');
M_.param_names_long = char(M_.param_names_long, 'SIGMAc');
M_.param_names = char(M_.param_names, 'SIGMAinf');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAinf');
M_.param_names_long = char(M_.param_names_long, 'SIGMAinf');
M_.param_names = char(M_.param_names, 'SIGMAn');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAn');
M_.param_names_long = char(M_.param_names_long, 'SIGMAn');
M_.param_names = char(M_.param_names, 'SIGMAinff');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAinff');
M_.param_names_long = char(M_.param_names_long, 'SIGMAinff');
M_.param_names = char(M_.param_names, 'SIGMAx');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAx');
M_.param_names_long = char(M_.param_names_long, 'SIGMAx');
M_.param_names = char(M_.param_names, 'SIGMAg');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAg');
M_.param_names_long = char(M_.param_names_long, 'SIGMAg');
M_.param_names = char(M_.param_names, 'SIGMAw');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAw');
M_.param_names_long = char(M_.param_names_long, 'SIGMAw');
M_.param_names = char(M_.param_names, 'SIGMAcp');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAcp');
M_.param_names_long = char(M_.param_names_long, 'SIGMAcp');
M_.param_names = char(M_.param_names, 'a11');
M_.param_names_tex = char(M_.param_names_tex, 'a11');
M_.param_names_long = char(M_.param_names_long, 'a11');
M_.param_names = char(M_.param_names, 'a12');
M_.param_names_tex = char(M_.param_names_tex, 'a12');
M_.param_names_long = char(M_.param_names_long, 'a12');
M_.param_names = char(M_.param_names, 'a13');
M_.param_names_tex = char(M_.param_names_tex, 'a13');
M_.param_names_long = char(M_.param_names_long, 'a13');
M_.param_names = char(M_.param_names, 'a21');
M_.param_names_tex = char(M_.param_names_tex, 'a21');
M_.param_names_long = char(M_.param_names_long, 'a21');
M_.param_names = char(M_.param_names, 'a22');
M_.param_names_tex = char(M_.param_names_tex, 'a22');
M_.param_names_long = char(M_.param_names_long, 'a22');
M_.param_names = char(M_.param_names, 'a23');
M_.param_names_tex = char(M_.param_names_tex, 'a23');
M_.param_names_long = char(M_.param_names_long, 'a23');
M_.param_names = char(M_.param_names, 'a31');
M_.param_names_tex = char(M_.param_names_tex, 'a31');
M_.param_names_long = char(M_.param_names_long, 'a31');
M_.param_names = char(M_.param_names, 'a32');
M_.param_names_tex = char(M_.param_names_tex, 'a32');
M_.param_names_long = char(M_.param_names_long, 'a32');
M_.param_names = char(M_.param_names, 'a33');
M_.param_names_tex = char(M_.param_names_tex, 'a33');
M_.param_names_long = char(M_.param_names_long, 'a33');
M_.param_names = char(M_.param_names, 'phi_g');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_g');
M_.param_names_long = char(M_.param_names_long, 'phi_g');
M_.exo_det_nbr = 0;
M_.exo_nbr = 18;
M_.endo_nbr = 104;
M_.param_nbr = 72;
M_.orig_endo_nbr = 101;
M_.aux_vars(1).endo_index = 102;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 1;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(2).endo_index = 103;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 1;
M_.aux_vars(2).orig_lead_lag = -2;
M_.aux_vars(3).endo_index = 104;
M_.aux_vars(3).type = 1;
M_.aux_vars(3).orig_index = 1;
M_.aux_vars(3).orig_lead_lag = -3;
options_.varobs = [];
options_.varobs = 'Y_obs';
options_.varobs = char(options_.varobs, 'R_obs');
options_.varobs = char(options_.varobs, 'dP_obs');
options_.varobs = char(options_.varobs, 'C_obs');
options_.varobs = char(options_.varobs, 'Inv_obs');
options_.varobs = char(options_.varobs, 'NN_obs');
options_.varobs = char(options_.varobs, 'X_obs');
options_.varobs = char(options_.varobs, 'S_obs');
options_.varobs = char(options_.varobs, 'W_obs');
options_.varobs = char(options_.varobs, 'Ystar_obs');
options_.varobs = char(options_.varobs, 'Rstar_obs');
options_.varobs = char(options_.varobs, 'Pistar_obs');
options_.varobs = char(options_.varobs, 'G_obs');
options_.varobs = char(options_.varobs, 'dPx_obs');
options_.varobs_id = [ 63 64 65 66 67 68 70 72 76 73 74 75 77 79  ];
M_.Sigma_e = zeros(18, 18);
M_.Correlation_matrix = eye(18, 18);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('BOKDSGE2014_0722_static');
erase_compiled_function('BOKDSGE2014_0722_dynamic');
M_.lead_lag_incidence = [
 1 42 0;
 2 43 146;
 0 44 0;
 3 45 0;
 4 46 0;
 0 47 0;
 5 48 0;
 6 49 147;
 0 50 148;
 7 51 0;
 0 52 0;
 0 53 0;
 0 54 149;
 0 55 150;
 8 56 0;
 9 57 0;
 10 58 0;
 11 59 0;
 0 60 151;
 0 61 0;
 0 62 0;
 12 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 13 67 152;
 14 68 153;
 0 69 154;
 15 70 0;
 0 71 0;
 0 72 0;
 16 73 0;
 0 74 0;
 17 75 155;
 18 76 156;
 19 77 0;
 20 78 0;
 0 79 157;
 0 80 158;
 0 81 0;
 0 82 0;
 21 83 0;
 0 84 0;
 0 85 0;
 22 86 159;
 0 87 160;
 0 88 161;
 0 89 0;
 23 90 0;
 24 91 0;
 25 92 0;
 26 93 0;
 27 94 162;
 28 95 163;
 29 96 0;
 30 97 0;
 31 98 0;
 32 99 0;
 33 100 0;
 34 101 0;
 35 102 0;
 36 103 0;
 0 104 0;
 0 105 0;
 0 106 0;
 0 107 0;
 0 108 0;
 0 109 0;
 0 110 0;
 0 111 0;
 0 112 0;
 0 113 0;
 0 114 0;
 0 115 0;
 0 116 0;
 0 117 0;
 0 118 0;
 0 119 0;
 0 120 0;
 0 121 0;
 0 122 0;
 0 123 164;
 0 124 0;
 0 125 0;
 0 126 0;
 0 127 0;
 37 128 0;
 0 129 0;
 0 130 165;
 0 131 166;
 0 132 0;
 0 133 0;
 0 134 167;
 0 135 0;
 0 136 168;
 0 137 0;
 0 138 0;
 0 139 0;
 38 140 0;
 0 141 0;
 0 142 0;
 39 143 0;
 40 144 0;
 41 145 0;]';
M_.nstatic = 49;
M_.nfwrd   = 14;
M_.npred   = 32;
M_.nboth   = 9;
M_.nsfwrd   = 23;
M_.nspred   = 41;
M_.ndynamic   = 55;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:18];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(104, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(18, 1);
M_.params = NaN(72, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 484;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
M_.params( 1 ) = 0.999;
bet = M_.params( 1 );
M_.params( 2 ) = 0.025;
del = M_.params( 2 );
M_.params( 18 ) = 0.0095;
gamma = M_.params( 18 );
M_.params( 5 ) = 0.6909;
chic = M_.params( 5 );
M_.params( 17 ) = 3.339;
chik = M_.params( 17 );
M_.params( 26 ) = 0.025;
del_e = M_.params( 26 );
M_.params( 3 ) = 2;
psi = M_.params( 3 );
M_.params( 4 ) = 0.33;
alpk = M_.params( 4 );
M_.params( 8 ) = 0.807;
the = M_.params( 8 );
M_.params( 9 ) = 0.546;
thef = M_.params( 9 );
M_.params( 29 ) = 0.541;
thew = M_.params( 29 );
M_.params( 10 ) = 0.4019;
rhop = M_.params( 10 );
M_.params( 11 ) = 0.312;
rhoy = M_.params( 11 );
M_.params( 12 ) = 0.9407;
rhor = M_.params( 12 );
M_.params( 6 ) = 6.454;
eps = M_.params( 6 );
M_.params( 7 ) = 5.175;
epsf = M_.params( 7 );
M_.params( 30 ) = 6.091;
epsw = M_.params( 30 );
M_.params( 27 ) = 0.3162;
iota = M_.params( 27 );
M_.params( 15 ) = 0.4880;
psi_x = M_.params( 15 );
M_.params( 16 ) = 0.3945;
psi_px = M_.params( 16 );
M_.params( 13 ) = 0.165;
phi = M_.params( 13 );
M_.params( 14 ) = 0.03;
zet = M_.params( 14 );
M_.params( 34 ) = 0.5;
zet2 = M_.params( 34 );
M_.params( 25 ) = 1.2;
eta = M_.params( 25 );
M_.params( 19 ) = 0.975;
gamma1 = M_.params( 19 );
M_.params( 20 ) = 0.05;
omega = M_.params( 20 );
M_.params( 21 ) = 0.56723;
alp_c = M_.params( 21 );
M_.params( 22 ) = 3.955;
rho_c = M_.params( 22 );
M_.params( 23 ) = 0.35088;
alp_i = M_.params( 23 );
M_.params( 24 ) = 1.673;
rho_i = M_.params( 24 );
M_.params( 46 ) = 0.20;
g_ss = M_.params( 46 );
M_.params( 28 ) = 1.005;
pi_target = M_.params( 28 );
M_.params( 31 ) = 1;
v = M_.params( 31 );
M_.params( 32 ) = 0.02;
gam = M_.params( 32 );
M_.params( 33 ) = 1.2;
gam2 = M_.params( 33 );
M_.params( 35 ) = 0.45550;
alpx = M_.params( 35 );
M_.params( 36 ) = 1.488;
etax = M_.params( 36 );
M_.params( 72 ) = 1;
phi_g = M_.params( 72 );
M_.params( 37 ) = 0.8180;
rhogam = M_.params( 37 );
M_.params( 38 ) = 0.9459;
rhoa = M_.params( 38 );
M_.params( 39 ) = 0.9273;
rhoinv = M_.params( 39 );
M_.params( 40 ) = 0.6902;
rhoc = M_.params( 40 );
M_.params( 41 ) = 0.3224;
rhoinf = M_.params( 41 );
M_.params( 42 ) = 0.7981;
rhon = M_.params( 42 );
M_.params( 43 ) = 0.9325;
rhoinff = M_.params( 43 );
M_.params( 44 ) = 0.8402;
rhox = M_.params( 44 );
M_.params( 45 ) = 0.6705;
rhopinv = M_.params( 45 );
M_.params( 47 ) = 0.8052;
rhog = M_.params( 47 );
M_.params( 49 ) = 0.4684;
rhow = M_.params( 49 );
M_.params( 50 ) = 0.90716;
rhocp = M_.params( 50 );
M_.params( 51 ) = 0.0;
rhomc = M_.params( 51 );
M_.params( 52 ) = 0.0014;
SIGMAr = M_.params( 52 );
M_.params( 53 ) = 0.0091;
SIGMAa = M_.params( 53 );
M_.params( 54 ) = 0.1186;
SIGMAinv = M_.params( 54 );
M_.params( 55 ) = 0.0261;
SIGMAc = M_.params( 55 );
M_.params( 56 ) = 0.0122;
SIGMAinf = M_.params( 56 );
M_.params( 57 ) = 0.0034;
SIGMAn = M_.params( 57 );
M_.params( 58 ) = 0.0502;
SIGMAinff = M_.params( 58 );
M_.params( 59 ) = 0.0291;
SIGMAx = M_.params( 59 );
M_.params( 60 ) = 0.0077;
SIGMAg = M_.params( 60 );
M_.params( 61 ) = 0.188501;
SIGMAw = M_.params( 61 );
M_.params( 62 ) = 0.0088;
SIGMAcp = M_.params( 62 );
M_.params( 63 ) = 0.8098;
a11 = M_.params( 63 );
M_.params( 64 ) = 0.0226;
a12 = M_.params( 64 );
M_.params( 65 ) = (-0.0408);
a13 = M_.params( 65 );
M_.params( 66 ) = 0.0374;
a21 = M_.params( 66 );
M_.params( 67 ) = 0.9396;
a22 = M_.params( 67 );
M_.params( 68 ) = (-0.0176);
a23 = M_.params( 68 );
M_.params( 69 ) = 0.1177;
a31 = M_.params( 69 );
M_.params( 70 ) = 0.0294;
a32 = M_.params( 70 );
M_.params( 71 ) = 0.5523;
a33 = M_.params( 71 );
options_.trend_coeff_ = {};
tmp1 = strmatch('C_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(18)';
tmp1 = strmatch('G_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(18)';
tmp1 = strmatch('Inv_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(18)';
tmp1 = strmatch('W_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(18)';
tmp1 = strmatch('X_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(18)';
tmp1 = strmatch('Y_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(18)';
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = 0.572716;
oo_.steady_state( 2 ) = 0.0854136;
oo_.steady_state( 3 ) = (-0.184133);
oo_.steady_state( 4 ) = log((1+M_.params(18))/M_.params(1));
oo_.steady_state( 5 ) = 0.161546;
oo_.steady_state( 6 ) = (-2.82762);
oo_.steady_state( 7 ) = 2.11885;
oo_.steady_state( 8 ) = M_.params(18);
oo_.steady_state( 9 ) = 0;
oo_.steady_state( 10 ) = (-1.03672);
oo_.steady_state( 11 ) = (-0.182322);
oo_.steady_state( 12 ) = 0;
oo_.steady_state( 13 ) = 1.74009;
oo_.steady_state( 14 ) = 1.92241;
oo_.steady_state( 15 ) = 0;
oo_.steady_state( 16 ) = (-0.286734);
oo_.steady_state( 17 ) = (-0.227666);
oo_.steady_state( 18 ) = 0.0125045;
oo_.steady_state( 19 ) = (-0.286735);
oo_.steady_state( 20 ) = 1.7212e-06;
oo_.steady_state( 21 ) = (-0.286734);
oo_.steady_state( 22 ) = (-0.631171);
oo_.steady_state( 23 ) = 4.00498e-07;
oo_.steady_state( 24 ) = 4.00498e-07;
oo_.steady_state( 25 ) = 0.0124597;
oo_.steady_state( 26 ) = 2.23411e-11;
oo_.steady_state( 27 ) = (-1.25595);
oo_.steady_state( 28 ) = 0.0348178;
oo_.steady_state( 29 ) = 1.89572;
oo_.steady_state( 30 ) = (-0.24304);
oo_.steady_state( 31 ) = (-1.16408);
oo_.steady_state( 32 ) = (-0.0351037);
oo_.steady_state( 33 ) = (-0.155084);
oo_.steady_state( 34 ) = 0;
oo_.steady_state( 35 ) = (-0.0990233);
oo_.steady_state( 38 ) = (-0.97575);
oo_.steady_state( 39 ) = (-0.638344);
oo_.steady_state( 40 ) = (-2.65812);
oo_.steady_state( 41 ) = (-1.5351);
oo_.steady_state( 42 ) = (-0.06606);
oo_.steady_state( 43 ) = (-0.0919085);
oo_.steady_state( 44 ) = 0;
oo_.steady_state( 45 ) = (-0.0432459);
oo_.steady_state( 46 ) = (-0.0223043);
oo_.steady_state( 47 ) = (-0.0223043);
oo_.steady_state( 48 ) = (-0.639335);
oo_.steady_state( 62 ) = 6;
oo_.steady_state( 80 ) = 0;
oo_.steady_state( 81 ) = (-0.0751586);
oo_.steady_state( 82 ) = (-0.423288);
oo_.steady_state( 83 ) = (-1.12738);
oo_.steady_state( 84 ) = 0.423288;
oo_.steady_state( 85 ) = 0.661244;
oo_.steady_state( 86 ) = 0.0125075;
oo_.steady_state( 87 ) = 2.07067;
oo_.steady_state( 88 ) = (-1.30431);
oo_.steady_state( 89 ) = (-3.24499);
oo_.steady_state( 90 ) = 0.036211;
oo_.steady_state( 91 ) = 0.161546;
oo_.steady_state( 92 ) = 1.19985;
oo_.steady_state( 96 ) = 0.0632151;
oo_.steady_state( 97 ) = (-1.6094379124341);
oo_.steady_state( 98 ) = (-1.6094379124341);
oo_.steady_state( 99 ) = 0;
oo_.steady_state(102)=oo_.steady_state(1);
oo_.steady_state(103)=oo_.steady_state(102);
oo_.steady_state(104)=oo_.steady_state(103);
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
steady;
resid;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(15, 15) = (M_.params(62))^2;
options_.irf = 30;
options_.order = 1;
var_list_=[];
var_list_ = 'Y';
var_list_ = char(var_list_, 'C');
var_list_ = char(var_list_, 'Inv');
var_list_ = char(var_list_, 'dP');
var_list_ = char(var_list_, 'R');
var_list_ = char(var_list_, 'X');
var_list_ = char(var_list_, 'S');
var_list_ = char(var_list_, 'F');
info = stoch_simul(var_list_);
global estim_params_
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_vals = [];
estim_params_.param_vals = [estim_params_.param_vals; 25, NaN, (-Inf), Inf, 2, 1.4, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, NaN, (-Inf), Inf, 2, 6, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, (-Inf), Inf, 2, 6, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, NaN, (-Inf), Inf, 2, 6, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, NaN, (-Inf), Inf, 1, 0.6, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, (-Inf), Inf, 1, 0.6, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, NaN, (-Inf), Inf, 1, 0.6, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, NaN, (-Inf), Inf, 3, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, NaN, (-Inf), Inf, 3, 4, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, NaN, (-Inf), Inf, 1, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, NaN, (-Inf), Inf, 1, 0.8, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, NaN, (-Inf), Inf, 1, 0.2, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, NaN, (-Inf), Inf, 2, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, NaN, (-Inf), Inf, 1, 0.6, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, NaN, (-Inf), Inf, 1, 0.6, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, NaN, (-Inf), Inf, 2, 2, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, NaN, (-Inf), Inf, 2, 2, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, NaN, (-Inf), Inf, 2, 2.5, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 72, NaN, (-Inf), Inf, 2, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 38, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 40, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 41, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 39, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 42, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 43, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 44, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 45, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 47, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 49, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 50, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 63, NaN, (-Inf), Inf, 3, 0.9, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 64, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 65, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 66, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 67, NaN, (-Inf), Inf, 3, 0.9, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 68, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 69, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 70, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 71, NaN, (-Inf), Inf, 3, 0.6, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 10, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 17, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 12, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 13, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 14, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 16, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 15, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 18, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
save('BOKDSGE2014_0722_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('BOKDSGE2014_0722_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('BOKDSGE2014_0722_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('BOKDSGE2014_0722_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('BOKDSGE2014_0722_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
