%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'narkk';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('narkk.log');
M_.exo_names = 'er';
M_.exo_names_tex = 'er';
M_.exo_names_long = 'er';
M_.exo_names = char(M_.exo_names, 'ea');
M_.exo_names_tex = char(M_.exo_names_tex, 'ea');
M_.exo_names_long = char(M_.exo_names_long, 'ea');
M_.exo_names = char(M_.exo_names, 'etr');
M_.exo_names_tex = char(M_.exo_names_tex, 'etr');
M_.exo_names_long = char(M_.exo_names_long, 'etr');
M_.exo_names = char(M_.exo_names, 'ei');
M_.exo_names_tex = char(M_.exo_names_tex, 'ei');
M_.exo_names_long = char(M_.exo_names_long, 'ei');
M_.exo_names = char(M_.exo_names, 'ec');
M_.exo_names_tex = char(M_.exo_names_tex, 'ec');
M_.exo_names_long = char(M_.exo_names_long, 'ec');
M_.exo_names = char(M_.exo_names, 'epi');
M_.exo_names_tex = char(M_.exo_names_tex, 'epi');
M_.exo_names_long = char(M_.exo_names_long, 'epi');
M_.exo_names = char(M_.exo_names, 'enw');
M_.exo_names_tex = char(M_.exo_names_tex, 'enw');
M_.exo_names_long = char(M_.exo_names_long, 'enw');
M_.exo_names = char(M_.exo_names, 'epif');
M_.exo_names_tex = char(M_.exo_names_tex, 'epif');
M_.exo_names_long = char(M_.exo_names_long, 'epif');
M_.exo_names = char(M_.exo_names, 'ex');
M_.exo_names_tex = char(M_.exo_names_tex, 'ex');
M_.exo_names_long = char(M_.exo_names_long, 'ex');
M_.exo_names = char(M_.exo_names, 'eg');
M_.exo_names_tex = char(M_.exo_names_tex, 'eg');
M_.exo_names_long = char(M_.exo_names_long, 'eg');
M_.exo_names = char(M_.exo_names, 'epr');
M_.exo_names_tex = char(M_.exo_names_tex, 'epr');
M_.exo_names_long = char(M_.exo_names_long, 'epr');
M_.exo_names = char(M_.exo_names, 'eystar');
M_.exo_names_tex = char(M_.exo_names_tex, 'eystar');
M_.exo_names_long = char(M_.exo_names_long, 'eystar');
M_.exo_names = char(M_.exo_names, 'erstar');
M_.exo_names_tex = char(M_.exo_names_tex, 'erstar');
M_.exo_names_long = char(M_.exo_names_long, 'erstar');
M_.exo_names = char(M_.exo_names, 'epistar');
M_.exo_names_tex = char(M_.exo_names_tex, 'epistar');
M_.exo_names_long = char(M_.exo_names_long, 'epistar');
M_.exo_names = char(M_.exo_names, 'ecp');
M_.exo_names_tex = char(M_.exo_names_tex, 'ecp');
M_.exo_names_long = char(M_.exo_names_long, 'ecp');
M_.exo_names = char(M_.exo_names, 'ew');
M_.exo_names_tex = char(M_.exo_names_tex, 'ew');
M_.exo_names_long = char(M_.exo_names_long, 'ew');
M_.exo_names = char(M_.exo_names, 'emc');
M_.exo_names_tex = char(M_.exo_names_tex, 'emc');
M_.exo_names_long = char(M_.exo_names_long, 'emc');
M_.exo_names = char(M_.exo_names, 'epx');
M_.exo_names_tex = char(M_.exo_names_tex, 'epx');
M_.exo_names_long = char(M_.exo_names_long, 'epx');
M_.exo_names = char(M_.exo_names, 'eq');
M_.exo_names_tex = char(M_.exo_names_tex, 'eq');
M_.exo_names_long = char(M_.exo_names_long, 'eq');
M_.endo_names = 'Y';
M_.endo_names_tex = 'Y';
M_.endo_names_long = 'Y';
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 'N');
M_.endo_names_tex = char(M_.endo_names_tex, 'N');
M_.endo_names_long = char(M_.endo_names_long, 'N');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'W');
M_.endo_names_tex = char(M_.endo_names_tex, 'W');
M_.endo_names_long = char(M_.endo_names_long, 'W');
M_.endo_names = char(M_.endo_names, 'Rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk');
M_.endo_names_long = char(M_.endo_names_long, 'Rk');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'dZtr');
M_.endo_names_tex = char(M_.endo_names_tex, 'dZtr');
M_.endo_names_long = char(M_.endo_names_long, 'dZtr');
M_.endo_names = char(M_.endo_names, 'dP');
M_.endo_names_tex = char(M_.endo_names_tex, 'dP');
M_.endo_names_long = char(M_.endo_names_long, 'dP');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'MC');
M_.endo_names_tex = char(M_.endo_names_tex, 'MC');
M_.endo_names_long = char(M_.endo_names_long, 'MC');
M_.endo_names = char(M_.endo_names, 'Phstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Phstar');
M_.endo_names_long = char(M_.endo_names_long, 'Phstar');
M_.endo_names = char(M_.endo_names, 'X1');
M_.endo_names_tex = char(M_.endo_names_tex, 'X1');
M_.endo_names_long = char(M_.endo_names_long, 'X1');
M_.endo_names = char(M_.endo_names, 'X2');
M_.endo_names_tex = char(M_.endo_names_tex, 'X2');
M_.endo_names_long = char(M_.endo_names_long, 'X2');
M_.endo_names = char(M_.endo_names, 'SS');
M_.endo_names_tex = char(M_.endo_names_tex, 'SS');
M_.endo_names_long = char(M_.endo_names_long, 'SS');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q');
M_.endo_names_long = char(M_.endo_names_long, 'Q');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'Rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rf');
M_.endo_names_long = char(M_.endo_names_long, 'Rf');
M_.endo_names = char(M_.endo_names, 'S');
M_.endo_names_tex = char(M_.endo_names_tex, 'S');
M_.endo_names_long = char(M_.endo_names_long, 'S');
M_.endo_names = char(M_.endo_names, 'Pxf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pxf');
M_.endo_names_long = char(M_.endo_names_long, 'Pxf');
M_.endo_names = char(M_.endo_names, 'Px');
M_.endo_names_tex = char(M_.endo_names_tex, 'Px');
M_.endo_names_long = char(M_.endo_names_long, 'Px');
M_.endo_names = char(M_.endo_names, 'Pm');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pm');
M_.endo_names_long = char(M_.endo_names_long, 'Pm');
M_.endo_names = char(M_.endo_names, 'X');
M_.endo_names_tex = char(M_.endo_names_tex, 'X');
M_.endo_names_long = char(M_.endo_names_long, 'X');
M_.endo_names = char(M_.endo_names, 'PPx');
M_.endo_names_tex = char(M_.endo_names_tex, 'PPx');
M_.endo_names_long = char(M_.endo_names_long, 'PPx');
M_.endo_names = char(M_.endo_names, 'PPm');
M_.endo_names_tex = char(M_.endo_names_tex, 'PPm');
M_.endo_names_long = char(M_.endo_names_long, 'PPm');
M_.endo_names = char(M_.endo_names, 'Rw');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rw');
M_.endo_names_long = char(M_.endo_names_long, 'Rw');
M_.endo_names = char(M_.endo_names, 'Xh');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xh');
M_.endo_names_long = char(M_.endo_names_long, 'Xh');
M_.endo_names = char(M_.endo_names, 'Xf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xf');
M_.endo_names_long = char(M_.endo_names_long, 'Xf');
M_.endo_names = char(M_.endo_names, 'dPx');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPx');
M_.endo_names_long = char(M_.endo_names_long, 'dPx');
M_.endo_names = char(M_.endo_names, 'Pk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pk');
M_.endo_names_long = char(M_.endo_names_long, 'Pk');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'Re');
M_.endo_names_tex = char(M_.endo_names_tex, 'Re');
M_.endo_names_long = char(M_.endo_names_long, 'Re');
M_.endo_names = char(M_.endo_names, 'NW');
M_.endo_names_tex = char(M_.endo_names_tex, 'NW');
M_.endo_names_long = char(M_.endo_names_long, 'NW');
M_.endo_names = char(M_.endo_names, 'ut');
M_.endo_names_tex = char(M_.endo_names_tex, 'ut');
M_.endo_names_long = char(M_.endo_names_long, 'ut');
M_.endo_names = char(M_.endo_names, 'Wstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Wstar');
M_.endo_names_long = char(M_.endo_names_long, 'Wstar');
M_.endo_names = char(M_.endo_names, 'X1w');
M_.endo_names_tex = char(M_.endo_names_tex, 'X1w');
M_.endo_names_long = char(M_.endo_names_long, 'X1w');
M_.endo_names = char(M_.endo_names, 'X1ww');
M_.endo_names_tex = char(M_.endo_names_tex, 'X1ww');
M_.endo_names_long = char(M_.endo_names_long, 'X1ww');
M_.endo_names = char(M_.endo_names, 'X2w');
M_.endo_names_tex = char(M_.endo_names_tex, 'X2w');
M_.endo_names_long = char(M_.endo_names_long, 'X2w');
M_.endo_names = char(M_.endo_names, 'X2ww');
M_.endo_names_tex = char(M_.endo_names_tex, 'X2ww');
M_.endo_names_long = char(M_.endo_names_long, 'X2ww');
M_.endo_names = char(M_.endo_names, 'Ch');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ch');
M_.endo_names_long = char(M_.endo_names_long, 'Ch');
M_.endo_names = char(M_.endo_names, 'Cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cf');
M_.endo_names_long = char(M_.endo_names_long, 'Cf');
M_.endo_names = char(M_.endo_names, 'P');
M_.endo_names_tex = char(M_.endo_names_tex, 'P');
M_.endo_names_long = char(M_.endo_names_long, 'P');
M_.endo_names = char(M_.endo_names, 'Pcfstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pcfstar');
M_.endo_names_long = char(M_.endo_names_long, 'Pcfstar');
M_.endo_names = char(M_.endo_names, 'dPh');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPh');
M_.endo_names_long = char(M_.endo_names_long, 'dPh');
M_.endo_names = char(M_.endo_names, 'dPcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPcf');
M_.endo_names_long = char(M_.endo_names_long, 'dPcf');
M_.endo_names = char(M_.endo_names, 'Pcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pcf');
M_.endo_names_long = char(M_.endo_names_long, 'Pcf');
M_.endo_names = char(M_.endo_names, 'Pif');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pif');
M_.endo_names_long = char(M_.endo_names_long, 'Pif');
M_.endo_names = char(M_.endo_names, 'X1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'X1f');
M_.endo_names_long = char(M_.endo_names_long, 'X1f');
M_.endo_names = char(M_.endo_names, 'X2f');
M_.endo_names_tex = char(M_.endo_names_tex, 'X2f');
M_.endo_names_long = char(M_.endo_names_long, 'X2f');
M_.endo_names = char(M_.endo_names, 'Ih');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ih');
M_.endo_names_long = char(M_.endo_names_long, 'Ih');
M_.endo_names = char(M_.endo_names, 'If');
M_.endo_names_tex = char(M_.endo_names_tex, 'If');
M_.endo_names_long = char(M_.endo_names_long, 'If');
M_.endo_names = char(M_.endo_names, 'Pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pi');
M_.endo_names_long = char(M_.endo_names_long, 'Pi');
M_.endo_names = char(M_.endo_names, 'Pifstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pifstar');
M_.endo_names_long = char(M_.endo_names_long, 'Pifstar');
M_.endo_names = char(M_.endo_names, 'dPi');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPi');
M_.endo_names_long = char(M_.endo_names_long, 'dPi');
M_.endo_names = char(M_.endo_names, 'dPif');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPif');
M_.endo_names_long = char(M_.endo_names_long, 'dPif');
M_.endo_names = char(M_.endo_names, 'X1if');
M_.endo_names_tex = char(M_.endo_names_tex, 'X1if');
M_.endo_names_long = char(M_.endo_names_long, 'X1if');
M_.endo_names = char(M_.endo_names, 'X2if');
M_.endo_names_tex = char(M_.endo_names_tex, 'X2if');
M_.endo_names_long = char(M_.endo_names_long, 'X2if');
M_.endo_names = char(M_.endo_names, 'M');
M_.endo_names_tex = char(M_.endo_names_tex, 'M');
M_.endo_names_long = char(M_.endo_names_long, 'M');
M_.endo_names = char(M_.endo_names, 'Ystar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ystar');
M_.endo_names_long = char(M_.endo_names_long, 'Ystar');
M_.endo_names = char(M_.endo_names, 'Rstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar');
M_.endo_names = char(M_.endo_names, 'PIstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIstar');
M_.endo_names_long = char(M_.endo_names_long, 'PIstar');
M_.endo_names = char(M_.endo_names, 'Za');
M_.endo_names_tex = char(M_.endo_names_tex, 'Za');
M_.endo_names_long = char(M_.endo_names_long, 'Za');
M_.endo_names = char(M_.endo_names, 'Zi');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zi');
M_.endo_names_long = char(M_.endo_names_long, 'Zi');
M_.endo_names = char(M_.endo_names, 'Zc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zc');
M_.endo_names_long = char(M_.endo_names_long, 'Zc');
M_.endo_names = char(M_.endo_names, 'Zpi');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zpi');
M_.endo_names_long = char(M_.endo_names_long, 'Zpi');
M_.endo_names = char(M_.endo_names, 'Znw');
M_.endo_names_tex = char(M_.endo_names_tex, 'Znw');
M_.endo_names_long = char(M_.endo_names_long, 'Znw');
M_.endo_names = char(M_.endo_names, 'Zpif');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zpif');
M_.endo_names_long = char(M_.endo_names_long, 'Zpif');
M_.endo_names = char(M_.endo_names, 'Zx');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zx');
M_.endo_names_long = char(M_.endo_names_long, 'Zx');
M_.endo_names = char(M_.endo_names, 'Zg');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zg');
M_.endo_names_long = char(M_.endo_names_long, 'Zg');
M_.endo_names = char(M_.endo_names, 'Zw');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zw');
M_.endo_names_long = char(M_.endo_names_long, 'Zw');
M_.endo_names = char(M_.endo_names, 'Zcp');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zcp');
M_.endo_names_long = char(M_.endo_names_long, 'Zcp');
M_.endo_names = char(M_.endo_names, 'Zmc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zmc');
M_.endo_names_long = char(M_.endo_names_long, 'Zmc');
M_.endo_names = char(M_.endo_names, 'Zq');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zq');
M_.endo_names_long = char(M_.endo_names_long, 'Zq');
M_.endo_names = char(M_.endo_names, 'Y_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Y_obs');
M_.endo_names = char(M_.endo_names, 'R_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'R_obs');
M_.endo_names = char(M_.endo_names, 'dP_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'dP\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'dP_obs');
M_.endo_names = char(M_.endo_names, 'C_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'C_obs');
M_.endo_names = char(M_.endo_names, 'Inv_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Inv\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Inv_obs');
M_.endo_names = char(M_.endo_names, 'NN_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'NN\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'NN_obs');
M_.endo_names = char(M_.endo_names, 'dPcf_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPcf\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'dPcf_obs');
M_.endo_names = char(M_.endo_names, 'X_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'X\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'X_obs');
M_.endo_names = char(M_.endo_names, 'dPi_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPi\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'dPi_obs');
M_.endo_names = char(M_.endo_names, 'S_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'S\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'S_obs');
M_.endo_names = char(M_.endo_names, 'Ystar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ystar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Ystar_obs');
M_.endo_names = char(M_.endo_names, 'Rstar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar_obs');
M_.endo_names = char(M_.endo_names, 'Pistar_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pistar\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'Pistar_obs');
M_.endo_names = char(M_.endo_names, 'G_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'G\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'G_obs');
M_.endo_names = char(M_.endo_names, 'SP_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'SP\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'SP_obs');
M_.endo_names = char(M_.endo_names, 'dPx_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'dPx\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'dPx_obs');
M_.endo_names = char(M_.endo_names, 'dY');
M_.endo_names_tex = char(M_.endo_names_tex, 'dY');
M_.endo_names_long = char(M_.endo_names_long, 'dY');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'ch');
M_.endo_names_tex = char(M_.endo_names_tex, 'ch');
M_.endo_names_long = char(M_.endo_names_long, 'ch');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'pcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pcf');
M_.endo_names_long = char(M_.endo_names_long, 'pcf');
M_.endo_names = char(M_.endo_names, 'ph');
M_.endo_names_tex = char(M_.endo_names_tex, 'ph');
M_.endo_names_long = char(M_.endo_names_long, 'ph');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'mcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcf');
M_.endo_names_long = char(M_.endo_names_long, 'mcf');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'ih');
M_.endo_names_tex = char(M_.endo_names_tex, 'ih');
M_.endo_names_long = char(M_.endo_names_long, 'ih');
M_.endo_names = char(M_.endo_names, 'if');
M_.endo_names_tex = char(M_.endo_names_tex, 'if');
M_.endo_names_long = char(M_.endo_names_long, 'if');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'pif');
M_.endo_names_tex = char(M_.endo_names_tex, 'pif');
M_.endo_names_long = char(M_.endo_names_long, 'pif');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'xh');
M_.endo_names_tex = char(M_.endo_names_tex, 'xh');
M_.endo_names_long = char(M_.endo_names_long, 'xh');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'px');
M_.endo_names_tex = char(M_.endo_names_tex, 'px');
M_.endo_names_long = char(M_.endo_names_long, 'px');
M_.endo_names = char(M_.endo_names, 'pxf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pxf');
M_.endo_names_long = char(M_.endo_names_long, 'pxf');
M_.endo_names = char(M_.endo_names, 'xf');
M_.endo_names_tex = char(M_.endo_names_tex, 'xf');
M_.endo_names_long = char(M_.endo_names_long, 'xf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'f');
M_.endo_names_tex = char(M_.endo_names_tex, 'f');
M_.endo_names_long = char(M_.endo_names_long, 'f');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, 'm');
M_.endo_names_long = char(M_.endo_names_long, 'm');
M_.endo_names = char(M_.endo_names, 'Ygap');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ygap');
M_.endo_names_long = char(M_.endo_names_long, 'Ygap');
M_.endo_names = char(M_.endo_names, 'Rgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rgap');
M_.endo_names_long = char(M_.endo_names_long, 'Rgap');
M_.endo_names = char(M_.endo_names, 'ct');
M_.endo_names_tex = char(M_.endo_names_tex, 'ct');
M_.endo_names_long = char(M_.endo_names_long, 'ct');
M_.endo_names = char(M_.endo_names, 'rt');
M_.endo_names_tex = char(M_.endo_names_tex, 'rt');
M_.endo_names_long = char(M_.endo_names_long, 'rt');
M_.endo_names = char(M_.endo_names, 'wt');
M_.endo_names_tex = char(M_.endo_names_tex, 'wt');
M_.endo_names_long = char(M_.endo_names_long, 'wt');
M_.endo_names = char(M_.endo_names, 'kt');
M_.endo_names_tex = char(M_.endo_names_tex, 'kt');
M_.endo_names_long = char(M_.endo_names_long, 'kt');
M_.endo_names = char(M_.endo_names, 'nt');
M_.endo_names_tex = char(M_.endo_names_tex, 'nt');
M_.endo_names_long = char(M_.endo_names_long, 'nt');
M_.endo_names = char(M_.endo_names, 'mct');
M_.endo_names_tex = char(M_.endo_names_tex, 'mct');
M_.endo_names_long = char(M_.endo_names_long, 'mct');
M_.endo_names = char(M_.endo_names, 'yt');
M_.endo_names_tex = char(M_.endo_names_tex, 'yt');
M_.endo_names_long = char(M_.endo_names_long, 'yt');
M_.endo_names = char(M_.endo_names, 'rkt');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkt');
M_.endo_names_long = char(M_.endo_names_long, 'rkt');
M_.endo_names = char(M_.endo_names, 'it');
M_.endo_names_tex = char(M_.endo_names_tex, 'it');
M_.endo_names_long = char(M_.endo_names_long, 'it');
M_.endo_names = char(M_.endo_names, 'Ygapt');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ygapt');
M_.endo_names_long = char(M_.endo_names_long, 'Ygapt');
M_.endo_names = char(M_.endo_names, 'Rgapt');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rgapt');
M_.endo_names_long = char(M_.endo_names_long, 'Rgapt');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_3');
M_.param_names = 'BETA';
M_.param_names_tex = 'BETA';
M_.param_names_long = 'BETA';
M_.param_names = char(M_.param_names, 'DELTA');
M_.param_names_tex = char(M_.param_names_tex, 'DELTA');
M_.param_names_long = char(M_.param_names_long, 'DELTA');
M_.param_names = char(M_.param_names, 'CHIn');
M_.param_names_tex = char(M_.param_names_tex, 'CHIn');
M_.param_names_long = char(M_.param_names_long, 'CHIn');
M_.param_names = char(M_.param_names, 'ALPHAk');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHAk');
M_.param_names_long = char(M_.param_names_long, 'ALPHAk');
M_.param_names = char(M_.param_names, 'CHIc');
M_.param_names_tex = char(M_.param_names_tex, 'CHIc');
M_.param_names_long = char(M_.param_names_long, 'CHIc');
M_.param_names = char(M_.param_names, 'PSIh');
M_.param_names_tex = char(M_.param_names_tex, 'PSIh');
M_.param_names_long = char(M_.param_names_long, 'PSIh');
M_.param_names = char(M_.param_names, 'PSIf');
M_.param_names_tex = char(M_.param_names_tex, 'PSIf');
M_.param_names_long = char(M_.param_names_long, 'PSIf');
M_.param_names = char(M_.param_names, 'THETAh');
M_.param_names_tex = char(M_.param_names_tex, 'THETAh');
M_.param_names_long = char(M_.param_names_long, 'THETAh');
M_.param_names = char(M_.param_names, 'THETAf');
M_.param_names_tex = char(M_.param_names_tex, 'THETAf');
M_.param_names_long = char(M_.param_names_long, 'THETAf');
M_.param_names = char(M_.param_names, 'TAYLORpi');
M_.param_names_tex = char(M_.param_names_tex, 'TAYLORpi');
M_.param_names_long = char(M_.param_names_long, 'TAYLORpi');
M_.param_names = char(M_.param_names, 'TAYLORy');
M_.param_names_tex = char(M_.param_names_tex, 'TAYLORy');
M_.param_names_long = char(M_.param_names_long, 'TAYLORy');
M_.param_names = char(M_.param_names, 'TAYLORr');
M_.param_names_tex = char(M_.param_names_tex, 'TAYLORr');
M_.param_names_long = char(M_.param_names_long, 'TAYLORr');
M_.param_names = char(M_.param_names, 'UIPy');
M_.param_names_tex = char(M_.param_names_tex, 'UIPy');
M_.param_names_long = char(M_.param_names_long, 'UIPy');
M_.param_names = char(M_.param_names, 'UIPf');
M_.param_names_tex = char(M_.param_names_tex, 'UIPf');
M_.param_names_long = char(M_.param_names_long, 'UIPf');
M_.param_names = char(M_.param_names, 'PHIx');
M_.param_names_tex = char(M_.param_names_tex, 'PHIx');
M_.param_names_long = char(M_.param_names_long, 'PHIx');
M_.param_names = char(M_.param_names, 'XIh');
M_.param_names_tex = char(M_.param_names_tex, 'XIh');
M_.param_names_long = char(M_.param_names_long, 'XIh');
M_.param_names = char(M_.param_names, 'KAPPAi');
M_.param_names_tex = char(M_.param_names_tex, 'KAPPAi');
M_.param_names_long = char(M_.param_names_long, 'KAPPAi');
M_.param_names = char(M_.param_names, 'GAMMAtr');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMAtr');
M_.param_names_long = char(M_.param_names_long, 'GAMMAtr');
M_.param_names = char(M_.param_names, 'SP');
M_.param_names_tex = char(M_.param_names_tex, 'SP');
M_.param_names_long = char(M_.param_names_long, 'SP');
M_.param_names = char(M_.param_names, 'KAPPArp');
M_.param_names_tex = char(M_.param_names_tex, 'KAPPArp');
M_.param_names_long = char(M_.param_names_long, 'KAPPArp');
M_.param_names = char(M_.param_names, 'ALPHAc');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHAc');
M_.param_names_long = char(M_.param_names_long, 'ALPHAc');
M_.param_names = char(M_.param_names, 'XIc');
M_.param_names_tex = char(M_.param_names_tex, 'XIc');
M_.param_names_long = char(M_.param_names_long, 'XIc');
M_.param_names = char(M_.param_names, 'ALPHAi');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHAi');
M_.param_names_long = char(M_.param_names_long, 'ALPHAi');
M_.param_names = char(M_.param_names, 'XIi');
M_.param_names_tex = char(M_.param_names_tex, 'XIi');
M_.param_names_long = char(M_.param_names_long, 'XIi');
M_.param_names = char(M_.param_names, 'ETA');
M_.param_names_tex = char(M_.param_names_tex, 'ETA');
M_.param_names_long = char(M_.param_names_long, 'ETA');
M_.param_names = char(M_.param_names, 'IOTA');
M_.param_names_tex = char(M_.param_names_tex, 'IOTA');
M_.param_names_long = char(M_.param_names_long, 'IOTA');
M_.param_names = char(M_.param_names, 'IT');
M_.param_names_tex = char(M_.param_names_tex, 'IT');
M_.param_names_long = char(M_.param_names_long, 'IT');
M_.param_names = char(M_.param_names, 'THETAw');
M_.param_names_tex = char(M_.param_names_tex, 'THETAw');
M_.param_names_long = char(M_.param_names_long, 'THETAw');
M_.param_names = char(M_.param_names, 'PSIw');
M_.param_names_tex = char(M_.param_names_tex, 'PSIw');
M_.param_names_long = char(M_.param_names_long, 'PSIw');
M_.param_names = char(M_.param_names, 'v');
M_.param_names_tex = char(M_.param_names_tex, 'v');
M_.param_names_long = char(M_.param_names_long, 'v');
M_.param_names = char(M_.param_names, 'GAMMA1');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMA1');
M_.param_names_long = char(M_.param_names_long, 'GAMMA1');
M_.param_names = char(M_.param_names, 'GAMMA2');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMA2');
M_.param_names_long = char(M_.param_names_long, 'GAMMA2');
M_.param_names = char(M_.param_names, 'UIPr');
M_.param_names_tex = char(M_.param_names_tex, 'UIPr');
M_.param_names_long = char(M_.param_names_long, 'UIPr');
M_.param_names = char(M_.param_names, 'ALPHAx');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHAx');
M_.param_names_long = char(M_.param_names_long, 'ALPHAx');
M_.param_names = char(M_.param_names, 'XIx');
M_.param_names_tex = char(M_.param_names_tex, 'XIx');
M_.param_names_long = char(M_.param_names_long, 'XIx');
M_.param_names = char(M_.param_names, 'RHOtr');
M_.param_names_tex = char(M_.param_names_tex, 'RHOtr');
M_.param_names_long = char(M_.param_names_long, 'RHOtr');
M_.param_names = char(M_.param_names, 'RHOa');
M_.param_names_tex = char(M_.param_names_tex, 'RHOa');
M_.param_names_long = char(M_.param_names_long, 'RHOa');
M_.param_names = char(M_.param_names, 'RHOi');
M_.param_names_tex = char(M_.param_names_tex, 'RHOi');
M_.param_names_long = char(M_.param_names_long, 'RHOi');
M_.param_names = char(M_.param_names, 'RHOc');
M_.param_names_tex = char(M_.param_names_tex, 'RHOc');
M_.param_names_long = char(M_.param_names_long, 'RHOc');
M_.param_names = char(M_.param_names, 'RHOpi');
M_.param_names_tex = char(M_.param_names_tex, 'RHOpi');
M_.param_names_long = char(M_.param_names_long, 'RHOpi');
M_.param_names = char(M_.param_names, 'RHOnw');
M_.param_names_tex = char(M_.param_names_tex, 'RHOnw');
M_.param_names_long = char(M_.param_names_long, 'RHOnw');
M_.param_names = char(M_.param_names, 'RHOpif');
M_.param_names_tex = char(M_.param_names_tex, 'RHOpif');
M_.param_names_long = char(M_.param_names_long, 'RHOpif');
M_.param_names = char(M_.param_names, 'RHOx');
M_.param_names_tex = char(M_.param_names_tex, 'RHOx');
M_.param_names_long = char(M_.param_names_long, 'RHOx');
M_.param_names = char(M_.param_names, 'RHOpii');
M_.param_names_tex = char(M_.param_names_tex, 'RHOpii');
M_.param_names_long = char(M_.param_names_long, 'RHOpii');
M_.param_names = char(M_.param_names, 'Gss');
M_.param_names_tex = char(M_.param_names_tex, 'Gss');
M_.param_names_long = char(M_.param_names_long, 'Gss');
M_.param_names = char(M_.param_names, 'RHOg');
M_.param_names_tex = char(M_.param_names_tex, 'RHOg');
M_.param_names_long = char(M_.param_names_long, 'RHOg');
M_.param_names = char(M_.param_names, 'RHOw');
M_.param_names_tex = char(M_.param_names_tex, 'RHOw');
M_.param_names_long = char(M_.param_names_long, 'RHOw');
M_.param_names = char(M_.param_names, 'RHOcp');
M_.param_names_tex = char(M_.param_names_tex, 'RHOcp');
M_.param_names_long = char(M_.param_names_long, 'RHOcp');
M_.param_names = char(M_.param_names, 'RHOmc');
M_.param_names_tex = char(M_.param_names_tex, 'RHOmc');
M_.param_names_long = char(M_.param_names_long, 'RHOmc');
M_.param_names = char(M_.param_names, 'RHOq');
M_.param_names_tex = char(M_.param_names_tex, 'RHOq');
M_.param_names_long = char(M_.param_names_long, 'RHOq');
M_.param_names = char(M_.param_names, 'SIGMAr');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAr');
M_.param_names_long = char(M_.param_names_long, 'SIGMAr');
M_.param_names = char(M_.param_names, 'SIGMAa');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAa');
M_.param_names_long = char(M_.param_names_long, 'SIGMAa');
M_.param_names = char(M_.param_names, 'SIGMAi');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAi');
M_.param_names_long = char(M_.param_names_long, 'SIGMAi');
M_.param_names = char(M_.param_names, 'SIGMAc');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAc');
M_.param_names_long = char(M_.param_names_long, 'SIGMAc');
M_.param_names = char(M_.param_names, 'SIGMApi');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMApi');
M_.param_names_long = char(M_.param_names_long, 'SIGMApi');
M_.param_names = char(M_.param_names, 'SIGMAnw');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAnw');
M_.param_names_long = char(M_.param_names_long, 'SIGMAnw');
M_.param_names = char(M_.param_names, 'SIGMApif');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMApif');
M_.param_names_long = char(M_.param_names_long, 'SIGMApif');
M_.param_names = char(M_.param_names, 'SIGMAx');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAx');
M_.param_names_long = char(M_.param_names_long, 'SIGMAx');
M_.param_names = char(M_.param_names, 'SIGMAg');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAg');
M_.param_names_long = char(M_.param_names_long, 'SIGMAg');
M_.param_names = char(M_.param_names, 'SIGMAw');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAw');
M_.param_names_long = char(M_.param_names_long, 'SIGMAw');
M_.param_names = char(M_.param_names, 'SIGMAcp');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAcp');
M_.param_names_long = char(M_.param_names_long, 'SIGMAcp');
M_.param_names = char(M_.param_names, 'a11');
M_.param_names_tex = char(M_.param_names_tex, 'a11');
M_.param_names_long = char(M_.param_names_long, 'a11');
M_.param_names = char(M_.param_names, 'a12');
M_.param_names_tex = char(M_.param_names_tex, 'a12');
M_.param_names_long = char(M_.param_names_long, 'a12');
M_.param_names = char(M_.param_names, 'a13');
M_.param_names_tex = char(M_.param_names_tex, 'a13');
M_.param_names_long = char(M_.param_names_long, 'a13');
M_.param_names = char(M_.param_names, 'a21');
M_.param_names_tex = char(M_.param_names_tex, 'a21');
M_.param_names_long = char(M_.param_names_long, 'a21');
M_.param_names = char(M_.param_names, 'a22');
M_.param_names_tex = char(M_.param_names_tex, 'a22');
M_.param_names_long = char(M_.param_names_long, 'a22');
M_.param_names = char(M_.param_names, 'a23');
M_.param_names_tex = char(M_.param_names_tex, 'a23');
M_.param_names_long = char(M_.param_names_long, 'a23');
M_.param_names = char(M_.param_names, 'a31');
M_.param_names_tex = char(M_.param_names_tex, 'a31');
M_.param_names_long = char(M_.param_names_long, 'a31');
M_.param_names = char(M_.param_names, 'a32');
M_.param_names_tex = char(M_.param_names_tex, 'a32');
M_.param_names_long = char(M_.param_names_long, 'a32');
M_.param_names = char(M_.param_names, 'a33');
M_.param_names_tex = char(M_.param_names_tex, 'a33');
M_.param_names_long = char(M_.param_names_long, 'a33');
M_.param_names = char(M_.param_names, 'PHIg');
M_.param_names_tex = char(M_.param_names_tex, 'PHIg');
M_.param_names_long = char(M_.param_names_long, 'PHIg');
M_.exo_det_nbr = 0;
M_.exo_nbr = 19;
M_.endo_nbr = 135;
M_.param_nbr = 71;
M_.orig_endo_nbr = 132;
M_.aux_vars(1).endo_index = 133;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 1;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(2).endo_index = 134;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 1;
M_.aux_vars(2).orig_lead_lag = -2;
M_.aux_vars(3).endo_index = 135;
M_.aux_vars(3).type = 1;
M_.aux_vars(3).orig_index = 1;
M_.aux_vars(3).orig_lead_lag = -3;
options_.varobs = [];
options_.varobs = 'Y_obs';
options_.varobs = char(options_.varobs, 'R_obs');
options_.varobs = char(options_.varobs, 'dP_obs');
options_.varobs = char(options_.varobs, 'C_obs');
options_.varobs = char(options_.varobs, 'S_obs');
options_.varobs = char(options_.varobs, 'Ystar_obs');
options_.varobs = char(options_.varobs, 'Rstar_obs');
options_.varobs = char(options_.varobs, 'Pistar_obs');
options_.varobs_id = [ 74 75 76 77 83 84 85 86  ];
M_.Sigma_e = zeros(19, 19);
M_.Correlation_matrix = eye(19, 19);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('narkk_static');
erase_compiled_function('narkk_dynamic');
M_.lead_lag_incidence = [
 1 51 0;
 2 52 186;
 0 53 0;
 3 54 0;
 4 55 0;
 0 56 0;
 5 57 0;
 6 58 187;
 0 59 188;
 7 60 0;
 0 61 0;
 0 62 0;
 0 63 189;
 0 64 190;
 8 65 0;
 9 66 0;
 10 67 0;
 11 68 0;
 0 69 191;
 0 70 0;
 12 71 0;
 0 72 0;
 13 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 14 80 192;
 15 81 193;
 0 82 194;
 16 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 195;
 0 88 0;
 0 89 196;
 0 90 0;
 0 91 0;
 17 92 0;
 0 93 0;
 18 94 197;
 19 95 198;
 20 96 0;
 21 97 0;
 0 98 199;
 0 99 200;
 0 100 0;
 0 101 0;
 22 102 0;
 0 103 0;
 0 104 0;
 23 105 201;
 0 106 202;
 0 107 203;
 0 108 0;
 24 109 0;
 25 110 0;
 26 111 0;
 27 112 0;
 28 113 204;
 29 114 205;
 30 115 0;
 31 116 0;
 32 117 0;
 33 118 0;
 34 119 0;
 35 120 0;
 36 121 0;
 37 122 0;
 38 123 0;
 0 124 0;
 0 125 0;
 0 126 0;
 0 127 0;
 0 128 0;
 0 129 0;
 0 130 0;
 0 131 0;
 0 132 0;
 0 133 0;
 0 134 0;
 0 135 0;
 0 136 0;
 0 137 0;
 0 138 0;
 0 139 0;
 0 140 0;
 39 141 206;
 0 142 0;
 0 143 0;
 0 144 0;
 0 145 0;
 0 146 0;
 0 147 0;
 0 148 0;
 0 149 0;
 0 150 0;
 0 151 207;
 0 152 0;
 0 153 0;
 0 154 0;
 40 155 0;
 0 156 0;
 41 157 0;
 0 158 0;
 0 159 0;
 0 160 0;
 42 161 0;
 0 162 0;
 0 163 0;
 0 164 0;
 43 165 0;
 0 166 0;
 0 167 0;
 44 168 0;
 0 169 0;
 0 170 0;
 0 171 0;
 45 172 208;
 0 173 0;
 0 174 0;
 46 175 0;
 0 176 0;
 0 177 0;
 0 178 0;
 0 179 0;
 47 180 0;
 0 181 0;
 0 182 0;
 48 183 0;
 49 184 0;
 50 185 0;]';
M_.nstatic = 73;
M_.nfwrd   = 12;
M_.npred   = 39;
M_.nboth   = 11;
M_.nsfwrd   = 23;
M_.nspred   = 50;
M_.ndynamic   = 62;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:19];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(135, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(19, 1);
M_.params = NaN(71, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 614;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
M_.params( 1 ) = 0.999;
BETA = M_.params( 1 );
M_.params( 2 ) = 0.025;
DELTA = M_.params( 2 );
M_.params( 18 ) = 0.0095;
GAMMAtr = M_.params( 18 );
M_.params( 5 ) = 0.6909;
CHIc = M_.params( 5 );
M_.params( 17 ) = 3.339;
KAPPAi = M_.params( 17 );
M_.params( 3 ) = 2;
CHIn = M_.params( 3 );
M_.params( 4 ) = 0.33;
ALPHAk = M_.params( 4 );
M_.params( 8 ) = 0.807;
THETAh = M_.params( 8 );
M_.params( 9 ) = 0.546;
THETAf = M_.params( 9 );
M_.params( 28 ) = 0.541;
THETAw = M_.params( 28 );
M_.params( 10 ) = 0.4019;
TAYLORpi = M_.params( 10 );
M_.params( 11 ) = 0.312;
TAYLORy = M_.params( 11 );
M_.params( 12 ) = 0.9407;
TAYLORr = M_.params( 12 );
M_.params( 6 ) = 6.454;
PSIh = M_.params( 6 );
M_.params( 7 ) = 5.175;
PSIf = M_.params( 7 );
M_.params( 29 ) = 6.091;
PSIw = M_.params( 29 );
M_.params( 26 ) = 0.3162;
IOTA = M_.params( 26 );
M_.params( 15 ) = 0.4880;
PHIx = M_.params( 15 );
M_.params( 16 ) = 0.3945;
XIh = M_.params( 16 );
M_.params( 13 ) = 0.165;
UIPy = M_.params( 13 );
M_.params( 14 ) = 0.03;
UIPf = M_.params( 14 );
M_.params( 33 ) = 0.5;
UIPr = M_.params( 33 );
M_.params( 25 ) = 1.2;
ETA = M_.params( 25 );
M_.params( 19 ) = 0.975;
SP = M_.params( 19 );
M_.params( 20 ) = 0.05;
KAPPArp = M_.params( 20 );
M_.params( 21 ) = 0.56723;
ALPHAc = M_.params( 21 );
M_.params( 22 ) = 3.955;
XIc = M_.params( 22 );
M_.params( 23 ) = 0.35088;
ALPHAi = M_.params( 23 );
M_.params( 24 ) = 1.673;
XIi = M_.params( 24 );
M_.params( 45 ) = 0.20;
Gss = M_.params( 45 );
M_.params( 27 ) = 1.005;
IT = M_.params( 27 );
M_.params( 30 ) = 1;
v = M_.params( 30 );
M_.params( 31 ) = 0.02;
GAMMA1 = M_.params( 31 );
M_.params( 32 ) = 1.2;
GAMMA2 = M_.params( 32 );
M_.params( 34 ) = 0.45550;
ALPHAx = M_.params( 34 );
M_.params( 35 ) = 1.488;
XIx = M_.params( 35 );
M_.params( 71 ) = 1;
PHIg = M_.params( 71 );
M_.params( 36 ) = 0.8180;
RHOtr = M_.params( 36 );
M_.params( 37 ) = 0.9459;
RHOa = M_.params( 37 );
M_.params( 38 ) = 0.9273;
RHOi = M_.params( 38 );
M_.params( 39 ) = 0.6902;
RHOc = M_.params( 39 );
M_.params( 40 ) = 0.3224;
RHOpi = M_.params( 40 );
M_.params( 41 ) = 0.7981;
RHOnw = M_.params( 41 );
M_.params( 42 ) = 0.9325;
RHOpif = M_.params( 42 );
M_.params( 43 ) = 0.8402;
RHOx = M_.params( 43 );
M_.params( 44 ) = 0.6705;
RHOpii = M_.params( 44 );
M_.params( 46 ) = 0.8052;
RHOg = M_.params( 46 );
M_.params( 47 ) = 0.4684;
RHOw = M_.params( 47 );
M_.params( 48 ) = 0.90716;
RHOcp = M_.params( 48 );
M_.params( 49 ) = 0.5;
RHOmc = M_.params( 49 );
M_.params( 50 ) = 0.3;
RHOq = M_.params( 50 );
M_.params( 51 ) = 0.0014;
SIGMAr = M_.params( 51 );
M_.params( 52 ) = 0.0091;
SIGMAa = M_.params( 52 );
M_.params( 53 ) = 0.1186;
SIGMAi = M_.params( 53 );
M_.params( 54 ) = 0.0261;
SIGMAc = M_.params( 54 );
M_.params( 55 ) = 0.0122;
SIGMApi = M_.params( 55 );
M_.params( 56 ) = 0.0034;
SIGMAnw = M_.params( 56 );
M_.params( 57 ) = 0.0502;
SIGMApif = M_.params( 57 );
M_.params( 58 ) = 0.0291;
SIGMAx = M_.params( 58 );
M_.params( 59 ) = 0.0077;
SIGMAg = M_.params( 59 );
M_.params( 60 ) = 0.188501;
SIGMAw = M_.params( 60 );
M_.params( 61 ) = 0.0088;
SIGMAcp = M_.params( 61 );
M_.params( 62 ) = 0.8098;
a11 = M_.params( 62 );
M_.params( 63 ) = 0.0226;
a12 = M_.params( 63 );
M_.params( 64 ) = (-0.0408);
a13 = M_.params( 64 );
M_.params( 65 ) = 0.0374;
a21 = M_.params( 65 );
M_.params( 66 ) = 0.9396;
a22 = M_.params( 66 );
M_.params( 67 ) = (-0.0176);
a23 = M_.params( 67 );
M_.params( 68 ) = 0.1177;
a31 = M_.params( 68 );
M_.params( 69 ) = 0.0294;
a32 = M_.params( 69 );
M_.params( 70 ) = 0.5523;
a33 = M_.params( 70 );
options_.trend_coeff_ = {};
tmp1 = strmatch('C_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(18)';
tmp1 = strmatch('Y_obs',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(18)';
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = 0.572716;
oo_.steady_state( 2 ) = 0.0854136;
oo_.steady_state( 3 ) = (-0.184133);
oo_.steady_state( 4 ) = log((1+M_.params(18))/M_.params(1));
oo_.steady_state( 5 ) = 0.161546;
oo_.steady_state( 6 ) = (-2.82762);
oo_.steady_state( 7 ) = 2.11885;
oo_.steady_state( 8 ) = M_.params(18);
oo_.steady_state( 9 ) = 0;
oo_.steady_state( 10 ) = (-1.03672);
oo_.steady_state( 11 ) = (-0.182322);
oo_.steady_state( 12 ) = 0;
oo_.steady_state( 13 ) = 1.74009;
oo_.steady_state( 14 ) = 1.92241;
oo_.steady_state( 15 ) = 0;
oo_.steady_state( 16 ) = (-0.286734);
oo_.steady_state( 17 ) = (-0.227666);
oo_.steady_state( 18 ) = 0.0125045;
oo_.steady_state( 19 ) = (-0.286735);
oo_.steady_state( 20 ) = 1.7212e-06;
oo_.steady_state( 22 ) = (-0.286734);
oo_.steady_state( 23 ) = (-0.631171);
oo_.steady_state( 24 ) = 4.00498e-07;
oo_.steady_state( 25 ) = 4.00498e-07;
oo_.steady_state( 26 ) = 0.0124597;
oo_.steady_state( 30 ) = 2.23411e-11;
oo_.steady_state( 31 ) = (-1.25595);
oo_.steady_state( 32 ) = 0.0348178;
oo_.steady_state( 33 ) = 1.89572;
oo_.steady_state( 40 ) = (-0.24304);
oo_.steady_state( 41 ) = (-1.16408);
oo_.steady_state( 42 ) = (-0.0351037);
oo_.steady_state( 43 ) = (-0.155084);
oo_.steady_state( 44 ) = 0;
oo_.steady_state( 45 ) = (-0.0990233);
oo_.steady_state( 48 ) = (-0.97575);
oo_.steady_state( 49 ) = (-0.638344);
oo_.steady_state( 50 ) = (-2.65812);
oo_.steady_state( 51 ) = (-1.5351);
oo_.steady_state( 52 ) = (-0.06606);
oo_.steady_state( 53 ) = (-0.0919085);
oo_.steady_state( 54 ) = 0;
oo_.steady_state( 55 ) = (-0.0432459);
oo_.steady_state( 56 ) = (-0.0223043);
oo_.steady_state( 57 ) = (-0.0223043);
oo_.steady_state( 58 ) = (-0.639335);
oo_.steady_state( 72 ) = 0;
oo_.steady_state( 73 ) = 0;
oo_.steady_state( 35 ) = 0.161546;
oo_.steady_state( 36 ) = 1.19985;
oo_.steady_state( 34 ) = 0.0632151;
oo_.steady_state( 27 ) = (-1.6094379124341);
oo_.steady_state( 28 ) = (-1.6094379124341);
oo_.steady_state( 21 ) = 0;
oo_.steady_state( 91 ) = 0.846842;
oo_.steady_state( 92 ) = log((1+M_.params(18))/M_.params(1));
oo_.steady_state( 93 ) = 0.189781;
oo_.steady_state( 94 ) = 0.263982;
oo_.steady_state( 95 ) = (-0.24304);
oo_.steady_state( 96 ) = (-1.16408);
oo_.steady_state( 97 ) = (-0.155084);
oo_.steady_state( 98 ) = 0;
oo_.steady_state( 99 ) = (-0.182322);
oo_.steady_state( 101 ) = (-0.286734);
oo_.steady_state( 102 ) = (-2.65812);
oo_.steady_state( 103 ) = (-1.5351);
oo_.steady_state( 104 ) = (-0.06606);
oo_.steady_state( 105 ) = (-0.802684);
oo_.steady_state( 106 ) = (-0.0919085);
oo_.steady_state( 116 ) = (-2.81722);
oo_.steady_state( 117 ) = 0.0;
oo_.steady_state( 107 ) = 2.5723;
oo_.steady_state( 108 ) = 1.02259;
oo_.steady_state( 109 ) = (-1.6094379124341);
oo_.steady_state( 110 ) = (-1.03672);
oo_.steady_state( 111 ) = (-0.631171);
oo_.steady_state( 112 ) = 0;
oo_.steady_state( 114 ) = (-1.6094379124341);
oo_.steady_state( 115 ) = 0.0125045;
oo_.steady_state( 118 ) = (-0.227666);
oo_.steady_state( 119 ) = (-0.639335);
oo_.steady_state( 120 ) = 0;
oo_.steady_state( 121 ) = 0;
oo_.steady_state( 122 ) = 0.846842;
oo_.steady_state( 123 ) = log((1+M_.params(18))/M_.params(1));
oo_.steady_state( 124 ) = 0.189781;
oo_.steady_state( 125 ) = 2.5723;
oo_.steady_state( 126 ) = 0.263982;
oo_.steady_state( 127 ) = (-0.168351);
oo_.steady_state( 128 ) = 1.02259;
oo_.steady_state( 129 ) = (-2.81722);
oo_.steady_state( 130 ) = (-0.802684);
oo_.steady_state( 131 ) = 0;
oo_.steady_state( 132 ) = 0;
oo_.steady_state(133)=oo_.steady_state(1);
oo_.steady_state(134)=oo_.steady_state(133);
oo_.steady_state(135)=oo_.steady_state(134);
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
options_.solve_algo = 4;
steady;
resid;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(15, 15) = (M_.params(61))^2;
options_.irf = 40;
options_.order = 1;
var_list_=[];
var_list_ = 'Y';
var_list_ = char(var_list_, 'C');
var_list_ = char(var_list_, 'I');
var_list_ = char(var_list_, 'dP');
var_list_ = char(var_list_, 'R');
var_list_ = char(var_list_, 'X');
var_list_ = char(var_list_, 'S');
var_list_ = char(var_list_, 'F');
var_list_ = char(var_list_, 'Ygap');
var_list_ = char(var_list_, 'Rgap');
var_list_ = char(var_list_, 'y');
var_list_ = char(var_list_, 'r');
var_list_ = char(var_list_, 'i');
var_list_ = char(var_list_, 'f');
var_list_ = char(var_list_, 'yt');
var_list_ = char(var_list_, 'rt');
info = stoch_simul(var_list_);
global estim_params_
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_vals = [];
estim_params_.param_vals = [estim_params_.param_vals; 25, NaN, (-Inf), Inf, 2, 1.4, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, NaN, (-Inf), Inf, 2, 6, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, (-Inf), Inf, 2, 6, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, NaN, (-Inf), Inf, 2, 6, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, NaN, (-Inf), Inf, 1, 0.6, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, (-Inf), Inf, 1, 0.6, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, NaN, (-Inf), Inf, 1, 0.6, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, NaN, (-Inf), Inf, 3, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, NaN, (-Inf), Inf, 3, 4, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, NaN, (-Inf), Inf, 1, 0.3, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, NaN, (-Inf), Inf, 1, 0.8, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, NaN, (-Inf), Inf, 1, 0.2, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, NaN, (-Inf), Inf, 2, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, NaN, (-Inf), Inf, 1, 0.6, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, NaN, (-Inf), Inf, 1, 0.6, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, NaN, (-Inf), Inf, 2, 2, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, NaN, (-Inf), Inf, 2, 2, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, NaN, (-Inf), Inf, 2, 2.5, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 32, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, NaN, (-Inf), Inf, 1, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 71, NaN, (-Inf), Inf, 2, 0.5, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 39, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 40, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 38, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 41, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 42, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 43, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 44, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 46, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 47, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 48, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 49, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 50, NaN, (-Inf), Inf, 1, 0.8, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 62, NaN, (-Inf), Inf, 3, 0.9, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 63, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 64, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 65, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 66, NaN, (-Inf), Inf, 3, 0.9, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 67, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 68, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 69, NaN, (-Inf), Inf, 3, 0.0, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 70, NaN, (-Inf), Inf, 3, 0.6, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 10, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 17, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 12, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 13, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 14, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 16, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 15, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 18, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 19, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
options_.first_obs = 1;
options_.mh_drop = 0.4;
options_.mh_jscale = 0.20;
options_.mh_nblck = 1;
options_.mh_replic = 0;
options_.mode_compute = 4;
options_.nograph = 1;
options_.plot_priors = 0;
options_.smoother = 1;
options_.datafile = 'data_201444_cpi';
options_.order = 1;
var_list_=[];
var_list_ = 'Y_obs';
var_list_ = char(var_list_, 'R_obs');
var_list_ = char(var_list_, 'dP_obs');
var_list_ = char(var_list_, 'C_obs');
var_list_ = char(var_list_, 'Inv_obs');
var_list_ = char(var_list_, 'NN_obs');
var_list_ = char(var_list_, 'dPcf_obs');
var_list_ = char(var_list_, 'X_obs');
var_list_ = char(var_list_, 'dPi_obs');
var_list_ = char(var_list_, 'S_obs');
var_list_ = char(var_list_, 'Ystar_obs');
var_list_ = char(var_list_, 'Rstar_obs');
var_list_ = char(var_list_, 'Pistar_obs');
var_list_ = char(var_list_, 'dZtr');
var_list_ = char(var_list_, 'G_obs');
var_list_ = char(var_list_, 'Za');
var_list_ = char(var_list_, 'Zi');
var_list_ = char(var_list_, 'Zc');
var_list_ = char(var_list_, 'Zpi');
var_list_ = char(var_list_, 'Znw');
var_list_ = char(var_list_, 'Zpif');
var_list_ = char(var_list_, 'Zx');
var_list_ = char(var_list_, 'Zg');
var_list_ = char(var_list_, 'Zw');
var_list_ = char(var_list_, 'Zcp');
var_list_ = char(var_list_, 'Zmc');
var_list_ = char(var_list_, 'Ygap');
var_list_ = char(var_list_, 'Rgap');
var_list_ = char(var_list_, 'y');
var_list_ = char(var_list_, 'r');
var_list_ = char(var_list_, 'yt');
var_list_ = char(var_list_, 'rt');
var_list_ = char(var_list_, 'Ygapt');
var_list_ = char(var_list_, 'Rgapt');
dynare_estimation(var_list_);
var_list_=[];
var_list_ = 'Y_obs';
var_list_ = char(var_list_, 'C_obs');
var_list_ = char(var_list_, 'R_obs');
var_list_ = char(var_list_, 'dP_obs');
var_list_ = char(var_list_, 'S_obs');
var_list_ = char(var_list_, 'Ygap');
var_list_ = char(var_list_, 'Rgap');
var_list_ = char(var_list_, 'y');
var_list_ = char(var_list_, 'r');
var_list_ = char(var_list_, 'yt');
var_list_ = char(var_list_, 'rt');
var_list_ = char(var_list_, 'Ygapt');
var_list_ = char(var_list_, 'Rgapt');
oo_ = shock_decomposition(M_,oo_,options_,var_list_);
save('narkk_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('narkk_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('narkk_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('narkk_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('narkk_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
