%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'nark_fc1';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('nark_fc1.log');
M_.exo_names = 'er';
M_.exo_names_tex = 'er';
M_.exo_names_long = 'er';
M_.exo_names = char(M_.exo_names, 'ea');
M_.exo_names_tex = char(M_.exo_names_tex, 'ea');
M_.exo_names_long = char(M_.exo_names_long, 'ea');
M_.exo_names = char(M_.exo_names, 'etr');
M_.exo_names_tex = char(M_.exo_names_tex, 'etr');
M_.exo_names_long = char(M_.exo_names_long, 'etr');
M_.exo_names = char(M_.exo_names, 'ei');
M_.exo_names_tex = char(M_.exo_names_tex, 'ei');
M_.exo_names_long = char(M_.exo_names_long, 'ei');
M_.exo_names = char(M_.exo_names, 'ec');
M_.exo_names_tex = char(M_.exo_names_tex, 'ec');
M_.exo_names_long = char(M_.exo_names_long, 'ec');
M_.exo_names = char(M_.exo_names, 'epi');
M_.exo_names_tex = char(M_.exo_names_tex, 'epi');
M_.exo_names_long = char(M_.exo_names_long, 'epi');
M_.exo_names = char(M_.exo_names, 'enw');
M_.exo_names_tex = char(M_.exo_names_tex, 'enw');
M_.exo_names_long = char(M_.exo_names_long, 'enw');
M_.exo_names = char(M_.exo_names, 'epif');
M_.exo_names_tex = char(M_.exo_names_tex, 'epif');
M_.exo_names_long = char(M_.exo_names_long, 'epif');
M_.exo_names = char(M_.exo_names, 'ex');
M_.exo_names_tex = char(M_.exo_names_tex, 'ex');
M_.exo_names_long = char(M_.exo_names_long, 'ex');
M_.exo_names = char(M_.exo_names, 'eg');
M_.exo_names_tex = char(M_.exo_names_tex, 'eg');
M_.exo_names_long = char(M_.exo_names_long, 'eg');
M_.exo_names = char(M_.exo_names, 'epr');
M_.exo_names_tex = char(M_.exo_names_tex, 'epr');
M_.exo_names_long = char(M_.exo_names_long, 'epr');
M_.exo_names = char(M_.exo_names, 'eystar');
M_.exo_names_tex = char(M_.exo_names_tex, 'eystar');
M_.exo_names_long = char(M_.exo_names_long, 'eystar');
M_.exo_names = char(M_.exo_names, 'erstar');
M_.exo_names_tex = char(M_.exo_names_tex, 'erstar');
M_.exo_names_long = char(M_.exo_names_long, 'erstar');
M_.exo_names = char(M_.exo_names, 'epistar');
M_.exo_names_tex = char(M_.exo_names_tex, 'epistar');
M_.exo_names_long = char(M_.exo_names_long, 'epistar');
M_.exo_names = char(M_.exo_names, 'ecp');
M_.exo_names_tex = char(M_.exo_names_tex, 'ecp');
M_.exo_names_long = char(M_.exo_names_long, 'ecp');
M_.exo_names = char(M_.exo_names, 'ew');
M_.exo_names_tex = char(M_.exo_names_tex, 'ew');
M_.exo_names_long = char(M_.exo_names_long, 'ew');
M_.exo_names = char(M_.exo_names, 'emc');
M_.exo_names_tex = char(M_.exo_names_tex, 'emc');
M_.exo_names_long = char(M_.exo_names_long, 'emc');
M_.exo_names = char(M_.exo_names, 'epx');
M_.exo_names_tex = char(M_.exo_names_tex, 'epx');
M_.exo_names_long = char(M_.exo_names_long, 'epx');
M_.endo_names = 'c';
M_.endo_names_tex = 'c';
M_.endo_names_long = 'c';
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'Zmc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zmc');
M_.endo_names_long = char(M_.endo_names_long, 'Zmc');
M_.endo_names = char(M_.endo_names, 'dZtr');
M_.endo_names_tex = char(M_.endo_names_tex, 'dZtr');
M_.endo_names_long = char(M_.endo_names_long, 'dZtr');
M_.endo_names = char(M_.endo_names, 'Zw');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zw');
M_.endo_names_long = char(M_.endo_names_long, 'Zw');
M_.endo_names = char(M_.endo_names, 'Ystar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ystar');
M_.endo_names_long = char(M_.endo_names_long, 'Ystar');
M_.endo_names = char(M_.endo_names, 'Rstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar');
M_.endo_names = char(M_.endo_names, 'PIstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIstar');
M_.endo_names_long = char(M_.endo_names_long, 'PIstar');
M_.endo_names = char(M_.endo_names, 'q_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_f');
M_.endo_names_long = char(M_.endo_names_long, 'q_f');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'f');
M_.endo_names_tex = char(M_.endo_names_tex, 'f');
M_.endo_names_long = char(M_.endo_names_long, 'f');
M_.endo_names = char(M_.endo_names, 'Zcp');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zcp');
M_.endo_names_long = char(M_.endo_names_long, 'Zcp');
M_.param_names = 'BETA';
M_.param_names_tex = 'BETA';
M_.param_names_long = 'BETA';
M_.param_names = char(M_.param_names, 'DELTA');
M_.param_names_tex = char(M_.param_names_tex, 'DELTA');
M_.param_names_long = char(M_.param_names_long, 'DELTA');
M_.param_names = char(M_.param_names, 'CHIn');
M_.param_names_tex = char(M_.param_names_tex, 'CHIn');
M_.param_names_long = char(M_.param_names_long, 'CHIn');
M_.param_names = char(M_.param_names, 'ALPHAk');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHAk');
M_.param_names_long = char(M_.param_names_long, 'ALPHAk');
M_.param_names = char(M_.param_names, 'CHIc');
M_.param_names_tex = char(M_.param_names_tex, 'CHIc');
M_.param_names_long = char(M_.param_names_long, 'CHIc');
M_.param_names = char(M_.param_names, 'PSIh');
M_.param_names_tex = char(M_.param_names_tex, 'PSIh');
M_.param_names_long = char(M_.param_names_long, 'PSIh');
M_.param_names = char(M_.param_names, 'PSIf');
M_.param_names_tex = char(M_.param_names_tex, 'PSIf');
M_.param_names_long = char(M_.param_names_long, 'PSIf');
M_.param_names = char(M_.param_names, 'THETAh');
M_.param_names_tex = char(M_.param_names_tex, 'THETAh');
M_.param_names_long = char(M_.param_names_long, 'THETAh');
M_.param_names = char(M_.param_names, 'THETAf');
M_.param_names_tex = char(M_.param_names_tex, 'THETAf');
M_.param_names_long = char(M_.param_names_long, 'THETAf');
M_.param_names = char(M_.param_names, 'TAYLORpi');
M_.param_names_tex = char(M_.param_names_tex, 'TAYLORpi');
M_.param_names_long = char(M_.param_names_long, 'TAYLORpi');
M_.param_names = char(M_.param_names, 'TAYLORy');
M_.param_names_tex = char(M_.param_names_tex, 'TAYLORy');
M_.param_names_long = char(M_.param_names_long, 'TAYLORy');
M_.param_names = char(M_.param_names, 'TAYLORr');
M_.param_names_tex = char(M_.param_names_tex, 'TAYLORr');
M_.param_names_long = char(M_.param_names_long, 'TAYLORr');
M_.param_names = char(M_.param_names, 'UIPy');
M_.param_names_tex = char(M_.param_names_tex, 'UIPy');
M_.param_names_long = char(M_.param_names_long, 'UIPy');
M_.param_names = char(M_.param_names, 'UIPf');
M_.param_names_tex = char(M_.param_names_tex, 'UIPf');
M_.param_names_long = char(M_.param_names_long, 'UIPf');
M_.param_names = char(M_.param_names, 'PHIx');
M_.param_names_tex = char(M_.param_names_tex, 'PHIx');
M_.param_names_long = char(M_.param_names_long, 'PHIx');
M_.param_names = char(M_.param_names, 'XIh');
M_.param_names_tex = char(M_.param_names_tex, 'XIh');
M_.param_names_long = char(M_.param_names_long, 'XIh');
M_.param_names = char(M_.param_names, 'KAPPAi');
M_.param_names_tex = char(M_.param_names_tex, 'KAPPAi');
M_.param_names_long = char(M_.param_names_long, 'KAPPAi');
M_.param_names = char(M_.param_names, 'GAMMAtr');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMAtr');
M_.param_names_long = char(M_.param_names_long, 'GAMMAtr');
M_.param_names = char(M_.param_names, 'SP');
M_.param_names_tex = char(M_.param_names_tex, 'SP');
M_.param_names_long = char(M_.param_names_long, 'SP');
M_.param_names = char(M_.param_names, 'KAPPArp');
M_.param_names_tex = char(M_.param_names_tex, 'KAPPArp');
M_.param_names_long = char(M_.param_names_long, 'KAPPArp');
M_.param_names = char(M_.param_names, 'ALPHAc');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHAc');
M_.param_names_long = char(M_.param_names_long, 'ALPHAc');
M_.param_names = char(M_.param_names, 'XIc');
M_.param_names_tex = char(M_.param_names_tex, 'XIc');
M_.param_names_long = char(M_.param_names_long, 'XIc');
M_.param_names = char(M_.param_names, 'ALPHAi');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHAi');
M_.param_names_long = char(M_.param_names_long, 'ALPHAi');
M_.param_names = char(M_.param_names, 'XIi');
M_.param_names_tex = char(M_.param_names_tex, 'XIi');
M_.param_names_long = char(M_.param_names_long, 'XIi');
M_.param_names = char(M_.param_names, 'ETA');
M_.param_names_tex = char(M_.param_names_tex, 'ETA');
M_.param_names_long = char(M_.param_names_long, 'ETA');
M_.param_names = char(M_.param_names, 'IOTA');
M_.param_names_tex = char(M_.param_names_tex, 'IOTA');
M_.param_names_long = char(M_.param_names_long, 'IOTA');
M_.param_names = char(M_.param_names, 'IT');
M_.param_names_tex = char(M_.param_names_tex, 'IT');
M_.param_names_long = char(M_.param_names_long, 'IT');
M_.param_names = char(M_.param_names, 'THETAw');
M_.param_names_tex = char(M_.param_names_tex, 'THETAw');
M_.param_names_long = char(M_.param_names_long, 'THETAw');
M_.param_names = char(M_.param_names, 'PSIw');
M_.param_names_tex = char(M_.param_names_tex, 'PSIw');
M_.param_names_long = char(M_.param_names_long, 'PSIw');
M_.param_names = char(M_.param_names, 'v');
M_.param_names_tex = char(M_.param_names_tex, 'v');
M_.param_names_long = char(M_.param_names_long, 'v');
M_.param_names = char(M_.param_names, 'GAMMA1');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMA1');
M_.param_names_long = char(M_.param_names_long, 'GAMMA1');
M_.param_names = char(M_.param_names, 'GAMMA2');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMA2');
M_.param_names_long = char(M_.param_names_long, 'GAMMA2');
M_.param_names = char(M_.param_names, 'UIPr');
M_.param_names_tex = char(M_.param_names_tex, 'UIPr');
M_.param_names_long = char(M_.param_names_long, 'UIPr');
M_.param_names = char(M_.param_names, 'ALPHAx');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHAx');
M_.param_names_long = char(M_.param_names_long, 'ALPHAx');
M_.param_names = char(M_.param_names, 'XIx');
M_.param_names_tex = char(M_.param_names_tex, 'XIx');
M_.param_names_long = char(M_.param_names_long, 'XIx');
M_.param_names = char(M_.param_names, 'RHOtr');
M_.param_names_tex = char(M_.param_names_tex, 'RHOtr');
M_.param_names_long = char(M_.param_names_long, 'RHOtr');
M_.param_names = char(M_.param_names, 'RHOa');
M_.param_names_tex = char(M_.param_names_tex, 'RHOa');
M_.param_names_long = char(M_.param_names_long, 'RHOa');
M_.param_names = char(M_.param_names, 'RHOi');
M_.param_names_tex = char(M_.param_names_tex, 'RHOi');
M_.param_names_long = char(M_.param_names_long, 'RHOi');
M_.param_names = char(M_.param_names, 'RHOc');
M_.param_names_tex = char(M_.param_names_tex, 'RHOc');
M_.param_names_long = char(M_.param_names_long, 'RHOc');
M_.param_names = char(M_.param_names, 'RHOpi');
M_.param_names_tex = char(M_.param_names_tex, 'RHOpi');
M_.param_names_long = char(M_.param_names_long, 'RHOpi');
M_.param_names = char(M_.param_names, 'RHOnw');
M_.param_names_tex = char(M_.param_names_tex, 'RHOnw');
M_.param_names_long = char(M_.param_names_long, 'RHOnw');
M_.param_names = char(M_.param_names, 'RHOpif');
M_.param_names_tex = char(M_.param_names_tex, 'RHOpif');
M_.param_names_long = char(M_.param_names_long, 'RHOpif');
M_.param_names = char(M_.param_names, 'RHOx');
M_.param_names_tex = char(M_.param_names_tex, 'RHOx');
M_.param_names_long = char(M_.param_names_long, 'RHOx');
M_.param_names = char(M_.param_names, 'RHOpii');
M_.param_names_tex = char(M_.param_names_tex, 'RHOpii');
M_.param_names_long = char(M_.param_names_long, 'RHOpii');
M_.param_names = char(M_.param_names, 'Gss');
M_.param_names_tex = char(M_.param_names_tex, 'Gss');
M_.param_names_long = char(M_.param_names_long, 'Gss');
M_.param_names = char(M_.param_names, 'RHOg');
M_.param_names_tex = char(M_.param_names_tex, 'RHOg');
M_.param_names_long = char(M_.param_names_long, 'RHOg');
M_.param_names = char(M_.param_names, 'RHOw');
M_.param_names_tex = char(M_.param_names_tex, 'RHOw');
M_.param_names_long = char(M_.param_names_long, 'RHOw');
M_.param_names = char(M_.param_names, 'RHOcp');
M_.param_names_tex = char(M_.param_names_tex, 'RHOcp');
M_.param_names_long = char(M_.param_names_long, 'RHOcp');
M_.param_names = char(M_.param_names, 'RHOmc');
M_.param_names_tex = char(M_.param_names_tex, 'RHOmc');
M_.param_names_long = char(M_.param_names_long, 'RHOmc');
M_.param_names = char(M_.param_names, 'SIGMAr');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAr');
M_.param_names_long = char(M_.param_names_long, 'SIGMAr');
M_.param_names = char(M_.param_names, 'SIGMAa');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAa');
M_.param_names_long = char(M_.param_names_long, 'SIGMAa');
M_.param_names = char(M_.param_names, 'SIGMAi');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAi');
M_.param_names_long = char(M_.param_names_long, 'SIGMAi');
M_.param_names = char(M_.param_names, 'SIGMAc');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAc');
M_.param_names_long = char(M_.param_names_long, 'SIGMAc');
M_.param_names = char(M_.param_names, 'SIGMApi');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMApi');
M_.param_names_long = char(M_.param_names_long, 'SIGMApi');
M_.param_names = char(M_.param_names, 'SIGMAnw');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAnw');
M_.param_names_long = char(M_.param_names_long, 'SIGMAnw');
M_.param_names = char(M_.param_names, 'SIGMApif');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMApif');
M_.param_names_long = char(M_.param_names_long, 'SIGMApif');
M_.param_names = char(M_.param_names, 'SIGMAx');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAx');
M_.param_names_long = char(M_.param_names_long, 'SIGMAx');
M_.param_names = char(M_.param_names, 'SIGMAg');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAg');
M_.param_names_long = char(M_.param_names_long, 'SIGMAg');
M_.param_names = char(M_.param_names, 'SIGMAw');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAw');
M_.param_names_long = char(M_.param_names_long, 'SIGMAw');
M_.param_names = char(M_.param_names, 'SIGMAcp');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMAcp');
M_.param_names_long = char(M_.param_names_long, 'SIGMAcp');
M_.param_names = char(M_.param_names, 'a11');
M_.param_names_tex = char(M_.param_names_tex, 'a11');
M_.param_names_long = char(M_.param_names_long, 'a11');
M_.param_names = char(M_.param_names, 'a12');
M_.param_names_tex = char(M_.param_names_tex, 'a12');
M_.param_names_long = char(M_.param_names_long, 'a12');
M_.param_names = char(M_.param_names, 'a13');
M_.param_names_tex = char(M_.param_names_tex, 'a13');
M_.param_names_long = char(M_.param_names_long, 'a13');
M_.param_names = char(M_.param_names, 'a21');
M_.param_names_tex = char(M_.param_names_tex, 'a21');
M_.param_names_long = char(M_.param_names_long, 'a21');
M_.param_names = char(M_.param_names, 'a22');
M_.param_names_tex = char(M_.param_names_tex, 'a22');
M_.param_names_long = char(M_.param_names_long, 'a22');
M_.param_names = char(M_.param_names, 'a23');
M_.param_names_tex = char(M_.param_names_tex, 'a23');
M_.param_names_long = char(M_.param_names_long, 'a23');
M_.param_names = char(M_.param_names, 'a31');
M_.param_names_tex = char(M_.param_names_tex, 'a31');
M_.param_names_long = char(M_.param_names_long, 'a31');
M_.param_names = char(M_.param_names, 'a32');
M_.param_names_tex = char(M_.param_names_tex, 'a32');
M_.param_names_long = char(M_.param_names_long, 'a32');
M_.param_names = char(M_.param_names, 'a33');
M_.param_names_tex = char(M_.param_names_tex, 'a33');
M_.param_names_long = char(M_.param_names_long, 'a33');
M_.param_names = char(M_.param_names, 'PHIg');
M_.param_names_tex = char(M_.param_names_tex, 'PHIg');
M_.param_names_long = char(M_.param_names_long, 'PHIg');
M_.exo_det_nbr = 0;
M_.exo_nbr = 18;
M_.endo_nbr = 19;
M_.param_nbr = 70;
M_.orig_endo_nbr = 19;
M_.aux_vars = [];
M_.Sigma_e = zeros(18, 18);
M_.Correlation_matrix = eye(18, 18);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('nark_fc1_static');
erase_compiled_function('nark_fc1_dynamic');
M_.lead_lag_incidence = [
 1 12 31;
 0 13 0;
 0 14 0;
 0 15 0;
 0 16 0;
 2 17 0;
 0 18 0;
 0 19 0;
 0 20 0;
 3 21 0;
 4 22 32;
 5 23 0;
 6 24 0;
 7 25 0;
 8 26 0;
 0 27 33;
 9 28 0;
 10 29 0;
 11 30 0;]';
M_.nstatic = 7;
M_.nfwrd   = 1;
M_.npred   = 9;
M_.nboth   = 2;
M_.nsfwrd   = 3;
M_.nspred   = 11;
M_.ndynamic   = 12;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:18];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(19, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(18, 1);
M_.params = NaN(70, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 79;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
M_.params( 1 ) = 0.999;
BETA = M_.params( 1 );
M_.params( 2 ) = 0.025;
DELTA = M_.params( 2 );
M_.params( 18 ) = 0.0095;
GAMMAtr = M_.params( 18 );
M_.params( 5 ) = 0.6909;
CHIc = M_.params( 5 );
M_.params( 17 ) = 3.339;
KAPPAi = M_.params( 17 );
M_.params( 3 ) = 2;
CHIn = M_.params( 3 );
M_.params( 4 ) = 0.33;
ALPHAk = M_.params( 4 );
M_.params( 8 ) = 0.807;
THETAh = M_.params( 8 );
M_.params( 9 ) = 0.546;
THETAf = M_.params( 9 );
M_.params( 28 ) = 0.541;
THETAw = M_.params( 28 );
M_.params( 10 ) = 0.4019;
TAYLORpi = M_.params( 10 );
M_.params( 11 ) = 0.312;
TAYLORy = M_.params( 11 );
M_.params( 12 ) = 0.9407;
TAYLORr = M_.params( 12 );
M_.params( 6 ) = 6.454;
PSIh = M_.params( 6 );
M_.params( 7 ) = 5.175;
PSIf = M_.params( 7 );
M_.params( 29 ) = 6.091;
PSIw = M_.params( 29 );
M_.params( 26 ) = 0.3162;
IOTA = M_.params( 26 );
M_.params( 15 ) = 0.4880;
PHIx = M_.params( 15 );
M_.params( 16 ) = 0.3945;
XIh = M_.params( 16 );
M_.params( 13 ) = 0.165;
UIPy = M_.params( 13 );
M_.params( 14 ) = 0.03;
UIPf = M_.params( 14 );
M_.params( 33 ) = 0.5;
UIPr = M_.params( 33 );
M_.params( 25 ) = 1.2;
ETA = M_.params( 25 );
M_.params( 19 ) = 0.975;
SP = M_.params( 19 );
M_.params( 20 ) = 0.05;
KAPPArp = M_.params( 20 );
M_.params( 21 ) = 0.56723;
ALPHAc = M_.params( 21 );
M_.params( 22 ) = 3.955;
XIc = M_.params( 22 );
M_.params( 23 ) = 0.35088;
ALPHAi = M_.params( 23 );
M_.params( 24 ) = 1.673;
XIi = M_.params( 24 );
M_.params( 45 ) = 0.20;
Gss = M_.params( 45 );
M_.params( 27 ) = 1.005;
IT = M_.params( 27 );
M_.params( 30 ) = 1;
v = M_.params( 30 );
M_.params( 31 ) = 0.02;
GAMMA1 = M_.params( 31 );
M_.params( 32 ) = 1.2;
GAMMA2 = M_.params( 32 );
M_.params( 34 ) = 0.45550;
ALPHAx = M_.params( 34 );
M_.params( 35 ) = 1.488;
XIx = M_.params( 35 );
M_.params( 70 ) = 1;
PHIg = M_.params( 70 );
M_.params( 36 ) = 0.8180;
RHOtr = M_.params( 36 );
M_.params( 37 ) = 0.9459;
RHOa = M_.params( 37 );
M_.params( 38 ) = 0.9273;
RHOi = M_.params( 38 );
M_.params( 39 ) = 0.6902;
RHOc = M_.params( 39 );
M_.params( 40 ) = 0.3224;
RHOpi = M_.params( 40 );
M_.params( 41 ) = 0.7981;
RHOnw = M_.params( 41 );
M_.params( 42 ) = 0.9325;
RHOpif = M_.params( 42 );
M_.params( 43 ) = 0.8402;
RHOx = M_.params( 43 );
M_.params( 44 ) = 0.6705;
RHOpii = M_.params( 44 );
M_.params( 46 ) = 0.8052;
RHOg = M_.params( 46 );
M_.params( 47 ) = 0.4684;
RHOw = M_.params( 47 );
M_.params( 48 ) = 0.90716;
RHOcp = M_.params( 48 );
M_.params( 49 ) = 0.0;
RHOmc = M_.params( 49 );
M_.params( 50 ) = 0.0014;
SIGMAr = M_.params( 50 );
M_.params( 51 ) = 0.0091;
SIGMAa = M_.params( 51 );
M_.params( 52 ) = 0.1186;
SIGMAi = M_.params( 52 );
M_.params( 53 ) = 0.0261;
SIGMAc = M_.params( 53 );
M_.params( 54 ) = 0.0122;
SIGMApi = M_.params( 54 );
M_.params( 55 ) = 0.0034;
SIGMAnw = M_.params( 55 );
M_.params( 56 ) = 0.0502;
SIGMApif = M_.params( 56 );
M_.params( 57 ) = 0.0291;
SIGMAx = M_.params( 57 );
M_.params( 58 ) = 0.0077;
SIGMAg = M_.params( 58 );
M_.params( 59 ) = 0.188501;
SIGMAw = M_.params( 59 );
M_.params( 60 ) = 0.0088;
SIGMAcp = M_.params( 60 );
M_.params( 61 ) = 0.8098;
a11 = M_.params( 61 );
M_.params( 62 ) = 0.0226;
a12 = M_.params( 62 );
M_.params( 63 ) = (-0.0408);
a13 = M_.params( 63 );
M_.params( 64 ) = 0.0374;
a21 = M_.params( 64 );
M_.params( 65 ) = 0.9396;
a22 = M_.params( 65 );
M_.params( 66 ) = (-0.0176);
a23 = M_.params( 66 );
M_.params( 67 ) = 0.1177;
a31 = M_.params( 67 );
M_.params( 68 ) = 0.0294;
a32 = M_.params( 68 );
M_.params( 69 ) = 0.5523;
a33 = M_.params( 69 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 2 ) = 0.7056;
oo_.steady_state( 1 ) = 1.02618;
oo_.steady_state( 3 ) = 0.44562;
oo_.steady_state( 4 ) = 0.327734;
oo_.steady_state( 5 ) = (-0.168351);
oo_.steady_state( 6 ) = 3.41132;
oo_.steady_state( 7 ) = 1.34218;
oo_.steady_state( 8 ) = 0.036335;
oo_.steady_state( 9 ) = (-3.33665);
oo_.steady_state( 10 ) = 6.454;
oo_.steady_state( 11 ) = 0.0095;
oo_.steady_state( 12 ) = 0;
oo_.steady_state( 13 ) = 0;
oo_.steady_state( 14 ) = 0;
oo_.steady_state( 15 ) = 0;
oo_.steady_state( 16 ) = (-8);
oo_.steady_state( 17 ) = 0;
oo_.steady_state( 18 ) = 0;
oo_.steady_state( 19 ) = 0;
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
steady;
resid;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(16, 16) = (M_.params(59))^2;
options_.irf = 30;
options_.order = 1;
var_list_=[];
var_list_ = 'y';
var_list_ = char(var_list_, 'c');
var_list_ = char(var_list_, 'mc');
var_list_ = char(var_list_, 'i');
var_list_ = char(var_list_, 'n');
var_list_ = char(var_list_, 'k');
var_list_ = char(var_list_, 'rk');
info = stoch_simul(var_list_);
save('nark_fc1_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('nark_fc1_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('nark_fc1_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('nark_fc1_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('nark_fc1_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
